package mavlink

type Protocol int

const (
	V2       Protocol = iota // 0 is default
	V1                       // 1 : fallback to V1
	V2Signed                 // 2 : sign
)

// Message is the interface implemented by the structs generated by mavgen from the XML dialect definitions.
type Message interface {
	ID() int
	CRCExtra() uint16
	MarshalV1([]byte) []byte
	MarshalV2([]byte) []byte
}
