// Code generated by "stringer -output strings.go -type=MavAutopilot,MavType,MavModeFlag,MavModeFlagDecodePosition,MavState,MavComponent"; DO NOT EDIT.

package minimal

import "strconv"

const _MavAutopilot_name = "MAV_AUTOPILOT_GENERICMAV_AUTOPILOT_RESERVEDMAV_AUTOPILOT_SLUGSMAV_AUTOPILOT_ARDUPILOTMEGAMAV_AUTOPILOT_OPENPILOTMAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLYMAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLYMAV_AUTOPILOT_GENERIC_MISSION_FULLMAV_AUTOPILOT_INVALIDMAV_AUTOPILOT_PPZMAV_AUTOPILOT_UDBMAV_AUTOPILOT_FPMAV_AUTOPILOT_PX4MAV_AUTOPILOT_SMACCMPILOTMAV_AUTOPILOT_AUTOQUADMAV_AUTOPILOT_ARMAZILAMAV_AUTOPILOT_AEROBMAV_AUTOPILOT_ASLUAVMAV_AUTOPILOT_SMARTAPMAV_AUTOPILOT_AIRRAILS"

var _MavAutopilot_index = [...]uint16{0, 21, 43, 62, 89, 112, 148, 206, 240, 261, 278, 295, 311, 328, 353, 375, 397, 416, 436, 457, 479}

func (i MavAutopilot) String() string {
	if i >= MavAutopilot(len(_MavAutopilot_index)-1) {
		return "MavAutopilot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MavAutopilot_name[_MavAutopilot_index[i]:_MavAutopilot_index[i+1]]
}

const _MavType_name = "MAV_TYPE_GENERICMAV_TYPE_FIXED_WINGMAV_TYPE_QUADROTORMAV_TYPE_COAXIALMAV_TYPE_HELICOPTERMAV_TYPE_ANTENNA_TRACKERMAV_TYPE_GCSMAV_TYPE_AIRSHIPMAV_TYPE_FREE_BALLOONMAV_TYPE_ROCKETMAV_TYPE_GROUND_ROVERMAV_TYPE_SURFACE_BOATMAV_TYPE_SUBMARINEMAV_TYPE_HEXAROTORMAV_TYPE_OCTOROTORMAV_TYPE_TRICOPTERMAV_TYPE_FLAPPING_WINGMAV_TYPE_KITEMAV_TYPE_ONBOARD_CONTROLLERMAV_TYPE_VTOL_DUOROTORMAV_TYPE_VTOL_QUADROTORMAV_TYPE_VTOL_TILTROTORMAV_TYPE_VTOL_RESERVED2MAV_TYPE_VTOL_RESERVED3MAV_TYPE_VTOL_RESERVED4MAV_TYPE_VTOL_RESERVED5MAV_TYPE_GIMBALMAV_TYPE_ADSBMAV_TYPE_PARAFOILMAV_TYPE_DODECAROTORMAV_TYPE_CAMERAMAV_TYPE_CHARGING_STATIONMAV_TYPE_FLARM"

var _MavType_index = [...]uint16{0, 16, 35, 53, 69, 88, 112, 124, 140, 161, 176, 197, 218, 236, 254, 272, 290, 312, 325, 352, 374, 397, 420, 443, 466, 489, 512, 527, 540, 557, 577, 592, 617, 631}

func (i MavType) String() string {
	if i >= MavType(len(_MavType_index)-1) {
		return "MavType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MavType_name[_MavType_index[i]:_MavType_index[i+1]]
}

const (
	_MavModeFlag_name_0 = "MAV_MODE_FLAG_CUSTOM_MODE_ENABLEDMAV_MODE_FLAG_TEST_ENABLED"
	_MavModeFlag_name_1 = "MAV_MODE_FLAG_AUTO_ENABLED"
	_MavModeFlag_name_2 = "MAV_MODE_FLAG_GUIDED_ENABLED"
	_MavModeFlag_name_3 = "MAV_MODE_FLAG_STABILIZE_ENABLED"
	_MavModeFlag_name_4 = "MAV_MODE_FLAG_HIL_ENABLED"
	_MavModeFlag_name_5 = "MAV_MODE_FLAG_MANUAL_INPUT_ENABLED"
	_MavModeFlag_name_6 = "MAV_MODE_FLAG_SAFETY_ARMED"
)

var (
	_MavModeFlag_index_0 = [...]uint8{0, 33, 59}
)

func (i MavModeFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MavModeFlag_name_0[_MavModeFlag_index_0[i]:_MavModeFlag_index_0[i+1]]
	case i == 4:
		return _MavModeFlag_name_1
	case i == 8:
		return _MavModeFlag_name_2
	case i == 16:
		return _MavModeFlag_name_3
	case i == 32:
		return _MavModeFlag_name_4
	case i == 64:
		return _MavModeFlag_name_5
	case i == 128:
		return _MavModeFlag_name_6
	default:
		return "MavModeFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const (
	_MavModeFlagDecodePosition_name_0 = "MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODEMAV_MODE_FLAG_DECODE_POSITION_TEST"
	_MavModeFlagDecodePosition_name_1 = "MAV_MODE_FLAG_DECODE_POSITION_AUTO"
	_MavModeFlagDecodePosition_name_2 = "MAV_MODE_FLAG_DECODE_POSITION_GUIDED"
	_MavModeFlagDecodePosition_name_3 = "MAV_MODE_FLAG_DECODE_POSITION_STABILIZE"
	_MavModeFlagDecodePosition_name_4 = "MAV_MODE_FLAG_DECODE_POSITION_HIL"
	_MavModeFlagDecodePosition_name_5 = "MAV_MODE_FLAG_DECODE_POSITION_MANUAL"
	_MavModeFlagDecodePosition_name_6 = "MAV_MODE_FLAG_DECODE_POSITION_SAFETY"
)

var (
	_MavModeFlagDecodePosition_index_0 = [...]uint8{0, 41, 75}
)

func (i MavModeFlagDecodePosition) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MavModeFlagDecodePosition_name_0[_MavModeFlagDecodePosition_index_0[i]:_MavModeFlagDecodePosition_index_0[i+1]]
	case i == 4:
		return _MavModeFlagDecodePosition_name_1
	case i == 8:
		return _MavModeFlagDecodePosition_name_2
	case i == 16:
		return _MavModeFlagDecodePosition_name_3
	case i == 32:
		return _MavModeFlagDecodePosition_name_4
	case i == 64:
		return _MavModeFlagDecodePosition_name_5
	case i == 128:
		return _MavModeFlagDecodePosition_name_6
	default:
		return "MavModeFlagDecodePosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const (
	_MavState_name_0 = "MAV_STATE_UNINIT"
	_MavState_name_1 = "MAV_STATE_BOOTMAV_STATE_CALIBRATINGMAV_STATE_STANDBYMAV_STATE_ACTIVEMAV_STATE_CRITICALMAV_STATE_EMERGENCYMAV_STATE_POWEROFFMAV_STATE_FLIGHT_TERMINATION"
)

var (
	_MavState_index_1 = [...]uint8{0, 14, 35, 52, 68, 86, 105, 123, 151}
)

func (i MavState) String() string {
	switch {
	case i == 0:
		return _MavState_name_0
	case 2 <= i && i <= 9:
		i -= 2
		return _MavState_name_1[_MavState_index_1[i]:_MavState_index_1[i+1]]
	default:
		return "MavState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const (
	_MavComponent_name_0 = "MAV_COMP_ID_ALLMAV_COMP_ID_AUTOPILOT1"
	_MavComponent_name_1 = "MAV_COMP_ID_CAMERAMAV_COMP_ID_CAMERA2MAV_COMP_ID_CAMERA3MAV_COMP_ID_CAMERA4MAV_COMP_ID_CAMERA5MAV_COMP_ID_CAMERA6"
	_MavComponent_name_2 = "MAV_COMP_ID_SERVO1MAV_COMP_ID_SERVO2MAV_COMP_ID_SERVO3MAV_COMP_ID_SERVO4MAV_COMP_ID_SERVO5MAV_COMP_ID_SERVO6MAV_COMP_ID_SERVO7MAV_COMP_ID_SERVO8MAV_COMP_ID_SERVO9MAV_COMP_ID_SERVO10MAV_COMP_ID_SERVO11MAV_COMP_ID_SERVO12MAV_COMP_ID_SERVO13MAV_COMP_ID_SERVO14MAV_COMP_ID_GIMBALMAV_COMP_ID_LOGMAV_COMP_ID_ADSBMAV_COMP_ID_OSDMAV_COMP_ID_PERIPHERALMAV_COMP_ID_QX1_GIMBALMAV_COMP_ID_FLARM"
	_MavComponent_name_3 = "MAV_COMP_ID_MISSIONPLANNER"
	_MavComponent_name_4 = "MAV_COMP_ID_PATHPLANNERMAV_COMP_ID_OBSTACLE_AVOIDANCEMAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY"
	_MavComponent_name_5 = "MAV_COMP_ID_IMUMAV_COMP_ID_IMU_2MAV_COMP_ID_IMU_3"
	_MavComponent_name_6 = "MAV_COMP_ID_GPSMAV_COMP_ID_GPS2"
	_MavComponent_name_7 = "MAV_COMP_ID_UDP_BRIDGEMAV_COMP_ID_UART_BRIDGE"
	_MavComponent_name_8 = "MAV_COMP_ID_SYSTEM_CONTROL"
)

var (
	_MavComponent_index_0 = [...]uint8{0, 15, 37}
	_MavComponent_index_1 = [...]uint8{0, 18, 37, 56, 75, 94, 113}
	_MavComponent_index_2 = [...]uint16{0, 18, 36, 54, 72, 90, 108, 126, 144, 162, 181, 200, 219, 238, 257, 275, 290, 306, 321, 343, 365, 382}
	_MavComponent_index_4 = [...]uint8{0, 23, 53, 89}
	_MavComponent_index_5 = [...]uint8{0, 15, 32, 49}
	_MavComponent_index_6 = [...]uint8{0, 15, 31}
	_MavComponent_index_7 = [...]uint8{0, 22, 45}
)

func (i MavComponent) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _MavComponent_name_0[_MavComponent_index_0[i]:_MavComponent_index_0[i+1]]
	case 100 <= i && i <= 105:
		i -= 100
		return _MavComponent_name_1[_MavComponent_index_1[i]:_MavComponent_index_1[i+1]]
	case 140 <= i && i <= 160:
		i -= 140
		return _MavComponent_name_2[_MavComponent_index_2[i]:_MavComponent_index_2[i+1]]
	case i == 190:
		return _MavComponent_name_3
	case 195 <= i && i <= 197:
		i -= 195
		return _MavComponent_name_4[_MavComponent_index_4[i]:_MavComponent_index_4[i+1]]
	case 200 <= i && i <= 202:
		i -= 200
		return _MavComponent_name_5[_MavComponent_index_5[i]:_MavComponent_index_5[i+1]]
	case 220 <= i && i <= 221:
		i -= 220
		return _MavComponent_name_6[_MavComponent_index_6[i]:_MavComponent_index_6[i+1]]
	case 240 <= i && i <= 241:
		i -= 240
		return _MavComponent_name_7[_MavComponent_index_7[i]:_MavComponent_index_7[i+1]]
	case i == 250:
		return _MavComponent_name_8
	default:
		return "MavComponent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
