// Generated enums and structures for Mavlink dialect icarous #0 version 0
// Generated by gomavlink, DO NOT EDIT.

#include "icarous.h"

// Internal function used by both serialisation and deserialisation.
uint8_t icarous_crcextra(enum ICAROUS_MESSAGE mid) {
  switch (mid) {
  case ICAROUS_MESSAGE_ICAROUS_HEARTBEAT:
    return 227;

  case ICAROUS_MESSAGE_ICAROUS_KINEMATIC_BANDS:
    return 239;
  }
  return 0;
}
