// Generated enums and structures for Mavlink dialect minimal #0 version 3
// Generated by gomavlink, DO NOT EDIT.
#include <stdarg.h>
#include <stdio.h>

#include "minimal.h"

static inline size_t psnprintf(char **pbuf, size_t *psize, const char *fmt,
                               ...) {
  va_list ap;
  va_start(ap, fmt);
  size_t s = vsnprintf(*pbuf, *psize, fmt, ap);
  if (s < *psize) {
    *pbuf += s;
    *psize -= s;
  } else {
    *psize = 0;
  }
  return s;
}

static const char *MAV_AUTOPILOT_str(enum MAV_AUTOPILOT val) {
  switch (val) {
  case MAV_AUTOPILOT_GENERIC:
    return "MAV_AUTOPILOT_GENERIC";
  case MAV_AUTOPILOT_RESERVED:
    return "MAV_AUTOPILOT_RESERVED";
  case MAV_AUTOPILOT_SLUGS:
    return "MAV_AUTOPILOT_SLUGS";
  case MAV_AUTOPILOT_ARDUPILOTMEGA:
    return "MAV_AUTOPILOT_ARDUPILOTMEGA";
  case MAV_AUTOPILOT_OPENPILOT:
    return "MAV_AUTOPILOT_OPENPILOT";
  case MAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLY:
    return "MAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLY";
  case MAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY:
    return "MAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY";
  case MAV_AUTOPILOT_GENERIC_MISSION_FULL:
    return "MAV_AUTOPILOT_GENERIC_MISSION_FULL";
  case MAV_AUTOPILOT_INVALID:
    return "MAV_AUTOPILOT_INVALID";
  case MAV_AUTOPILOT_PPZ:
    return "MAV_AUTOPILOT_PPZ";
  case MAV_AUTOPILOT_UDB:
    return "MAV_AUTOPILOT_UDB";
  case MAV_AUTOPILOT_FP:
    return "MAV_AUTOPILOT_FP";
  case MAV_AUTOPILOT_PX4:
    return "MAV_AUTOPILOT_PX4";
  case MAV_AUTOPILOT_SMACCMPILOT:
    return "MAV_AUTOPILOT_SMACCMPILOT";
  case MAV_AUTOPILOT_AUTOQUAD:
    return "MAV_AUTOPILOT_AUTOQUAD";
  case MAV_AUTOPILOT_ARMAZILA:
    return "MAV_AUTOPILOT_ARMAZILA";
  case MAV_AUTOPILOT_AEROB:
    return "MAV_AUTOPILOT_AEROB";
  case MAV_AUTOPILOT_ASLUAV:
    return "MAV_AUTOPILOT_ASLUAV";
  case MAV_AUTOPILOT_SMARTAP:
    return "MAV_AUTOPILOT_SMARTAP";
  case MAV_AUTOPILOT_AIRRAILS:
    return "MAV_AUTOPILOT_AIRRAILS";
  }
  return NULL;
};

static size_t psnprint_MAV_AUTOPILOT(char **p, size_t *sz,
                                     enum MAV_AUTOPILOT val) {
  const char *s = MAV_AUTOPILOT_str(val);
  if (s) {
    return psnprintf(p, sz, "%s", s);
  }
  return psnprintf(p, sz, "MAV_AUTOPILOT<%d>", (int)val);
}

static const char *MAV_TYPE_str(enum MAV_TYPE val) {
  switch (val) {
  case MAV_TYPE_GENERIC:
    return "MAV_TYPE_GENERIC";
  case MAV_TYPE_FIXED_WING:
    return "MAV_TYPE_FIXED_WING";
  case MAV_TYPE_QUADROTOR:
    return "MAV_TYPE_QUADROTOR";
  case MAV_TYPE_COAXIAL:
    return "MAV_TYPE_COAXIAL";
  case MAV_TYPE_HELICOPTER:
    return "MAV_TYPE_HELICOPTER";
  case MAV_TYPE_ANTENNA_TRACKER:
    return "MAV_TYPE_ANTENNA_TRACKER";
  case MAV_TYPE_GCS:
    return "MAV_TYPE_GCS";
  case MAV_TYPE_AIRSHIP:
    return "MAV_TYPE_AIRSHIP";
  case MAV_TYPE_FREE_BALLOON:
    return "MAV_TYPE_FREE_BALLOON";
  case MAV_TYPE_ROCKET:
    return "MAV_TYPE_ROCKET";
  case MAV_TYPE_GROUND_ROVER:
    return "MAV_TYPE_GROUND_ROVER";
  case MAV_TYPE_SURFACE_BOAT:
    return "MAV_TYPE_SURFACE_BOAT";
  case MAV_TYPE_SUBMARINE:
    return "MAV_TYPE_SUBMARINE";
  case MAV_TYPE_HEXAROTOR:
    return "MAV_TYPE_HEXAROTOR";
  case MAV_TYPE_OCTOROTOR:
    return "MAV_TYPE_OCTOROTOR";
  case MAV_TYPE_TRICOPTER:
    return "MAV_TYPE_TRICOPTER";
  case MAV_TYPE_FLAPPING_WING:
    return "MAV_TYPE_FLAPPING_WING";
  case MAV_TYPE_KITE:
    return "MAV_TYPE_KITE";
  case MAV_TYPE_ONBOARD_CONTROLLER:
    return "MAV_TYPE_ONBOARD_CONTROLLER";
  case MAV_TYPE_VTOL_DUOROTOR:
    return "MAV_TYPE_VTOL_DUOROTOR";
  case MAV_TYPE_VTOL_QUADROTOR:
    return "MAV_TYPE_VTOL_QUADROTOR";
  case MAV_TYPE_VTOL_TILTROTOR:
    return "MAV_TYPE_VTOL_TILTROTOR";
  case MAV_TYPE_VTOL_RESERVED2:
    return "MAV_TYPE_VTOL_RESERVED2";
  case MAV_TYPE_VTOL_RESERVED3:
    return "MAV_TYPE_VTOL_RESERVED3";
  case MAV_TYPE_VTOL_RESERVED4:
    return "MAV_TYPE_VTOL_RESERVED4";
  case MAV_TYPE_VTOL_RESERVED5:
    return "MAV_TYPE_VTOL_RESERVED5";
  case MAV_TYPE_GIMBAL:
    return "MAV_TYPE_GIMBAL";
  case MAV_TYPE_ADSB:
    return "MAV_TYPE_ADSB";
  case MAV_TYPE_PARAFOIL:
    return "MAV_TYPE_PARAFOIL";
  case MAV_TYPE_DODECAROTOR:
    return "MAV_TYPE_DODECAROTOR";
  case MAV_TYPE_CAMERA:
    return "MAV_TYPE_CAMERA";
  case MAV_TYPE_CHARGING_STATION:
    return "MAV_TYPE_CHARGING_STATION";
  case MAV_TYPE_FLARM:
    return "MAV_TYPE_FLARM";
  }
  return NULL;
};

static size_t psnprint_MAV_TYPE(char **p, size_t *sz, enum MAV_TYPE val) {
  const char *s = MAV_TYPE_str(val);
  if (s) {
    return psnprintf(p, sz, "%s", s);
  }
  return psnprintf(p, sz, "MAV_TYPE<%d>", (int)val);
}

static const char *MAV_MODE_FLAG_str(enum MAV_MODE_FLAG val) {
  switch (val) {
  case MAV_MODE_FLAG_SAFETY_ARMED:
    return "MAV_MODE_FLAG_SAFETY_ARMED";
  case MAV_MODE_FLAG_MANUAL_INPUT_ENABLED:
    return "MAV_MODE_FLAG_MANUAL_INPUT_ENABLED";
  case MAV_MODE_FLAG_HIL_ENABLED:
    return "MAV_MODE_FLAG_HIL_ENABLED";
  case MAV_MODE_FLAG_STABILIZE_ENABLED:
    return "MAV_MODE_FLAG_STABILIZE_ENABLED";
  case MAV_MODE_FLAG_GUIDED_ENABLED:
    return "MAV_MODE_FLAG_GUIDED_ENABLED";
  case MAV_MODE_FLAG_AUTO_ENABLED:
    return "MAV_MODE_FLAG_AUTO_ENABLED";
  case MAV_MODE_FLAG_TEST_ENABLED:
    return "MAV_MODE_FLAG_TEST_ENABLED";
  case MAV_MODE_FLAG_CUSTOM_MODE_ENABLED:
    return "MAV_MODE_FLAG_CUSTOM_MODE_ENABLED";
  }
  return NULL;
};

static size_t psnprint_MAV_MODE_FLAG(char **p, size_t *sz,
                                     enum MAV_MODE_FLAG val) {
  const char *s = MAV_MODE_FLAG_str(val);
  if (s) {
    return psnprintf(p, sz, "%s", s);
  }
  return psnprintf(p, sz, "MAV_MODE_FLAG<%d>", (int)val);
}

static const char *
MAV_MODE_FLAG_DECODE_POSITION_str(enum MAV_MODE_FLAG_DECODE_POSITION val) {
  switch (val) {
  case MAV_MODE_FLAG_DECODE_POSITION_SAFETY:
    return "MAV_MODE_FLAG_DECODE_POSITION_SAFETY";
  case MAV_MODE_FLAG_DECODE_POSITION_MANUAL:
    return "MAV_MODE_FLAG_DECODE_POSITION_MANUAL";
  case MAV_MODE_FLAG_DECODE_POSITION_HIL:
    return "MAV_MODE_FLAG_DECODE_POSITION_HIL";
  case MAV_MODE_FLAG_DECODE_POSITION_STABILIZE:
    return "MAV_MODE_FLAG_DECODE_POSITION_STABILIZE";
  case MAV_MODE_FLAG_DECODE_POSITION_GUIDED:
    return "MAV_MODE_FLAG_DECODE_POSITION_GUIDED";
  case MAV_MODE_FLAG_DECODE_POSITION_AUTO:
    return "MAV_MODE_FLAG_DECODE_POSITION_AUTO";
  case MAV_MODE_FLAG_DECODE_POSITION_TEST:
    return "MAV_MODE_FLAG_DECODE_POSITION_TEST";
  case MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODE:
    return "MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODE";
  }
  return NULL;
};

static size_t
psnprint_MAV_MODE_FLAG_DECODE_POSITION(char **p, size_t *sz,
                                       enum MAV_MODE_FLAG_DECODE_POSITION val) {
  const char *s = MAV_MODE_FLAG_DECODE_POSITION_str(val);
  if (s) {
    return psnprintf(p, sz, "%s", s);
  }
  return psnprintf(p, sz, "MAV_MODE_FLAG_DECODE_POSITION<%d>", (int)val);
}

static const char *MAV_STATE_str(enum MAV_STATE val) {
  switch (val) {
  case MAV_STATE_UNINIT:
    return "MAV_STATE_UNINIT";
  case MAV_STATE_BOOT:
    return "MAV_STATE_BOOT";
  case MAV_STATE_CALIBRATING:
    return "MAV_STATE_CALIBRATING";
  case MAV_STATE_STANDBY:
    return "MAV_STATE_STANDBY";
  case MAV_STATE_ACTIVE:
    return "MAV_STATE_ACTIVE";
  case MAV_STATE_CRITICAL:
    return "MAV_STATE_CRITICAL";
  case MAV_STATE_EMERGENCY:
    return "MAV_STATE_EMERGENCY";
  case MAV_STATE_POWEROFF:
    return "MAV_STATE_POWEROFF";
  case MAV_STATE_FLIGHT_TERMINATION:
    return "MAV_STATE_FLIGHT_TERMINATION";
  }
  return NULL;
};

static size_t psnprint_MAV_STATE(char **p, size_t *sz, enum MAV_STATE val) {
  const char *s = MAV_STATE_str(val);
  if (s) {
    return psnprintf(p, sz, "%s", s);
  }
  return psnprintf(p, sz, "MAV_STATE<%d>", (int)val);
}

static const char *MAV_COMPONENT_str(enum MAV_COMPONENT val) {
  switch (val) {
  case MAV_COMP_ID_ALL:
    return "MAV_COMP_ID_ALL";
  case MAV_COMP_ID_AUTOPILOT1:
    return "MAV_COMP_ID_AUTOPILOT1";
  case MAV_COMP_ID_CAMERA:
    return "MAV_COMP_ID_CAMERA";
  case MAV_COMP_ID_CAMERA2:
    return "MAV_COMP_ID_CAMERA2";
  case MAV_COMP_ID_CAMERA3:
    return "MAV_COMP_ID_CAMERA3";
  case MAV_COMP_ID_CAMERA4:
    return "MAV_COMP_ID_CAMERA4";
  case MAV_COMP_ID_CAMERA5:
    return "MAV_COMP_ID_CAMERA5";
  case MAV_COMP_ID_CAMERA6:
    return "MAV_COMP_ID_CAMERA6";
  case MAV_COMP_ID_SERVO1:
    return "MAV_COMP_ID_SERVO1";
  case MAV_COMP_ID_SERVO2:
    return "MAV_COMP_ID_SERVO2";
  case MAV_COMP_ID_SERVO3:
    return "MAV_COMP_ID_SERVO3";
  case MAV_COMP_ID_SERVO4:
    return "MAV_COMP_ID_SERVO4";
  case MAV_COMP_ID_SERVO5:
    return "MAV_COMP_ID_SERVO5";
  case MAV_COMP_ID_SERVO6:
    return "MAV_COMP_ID_SERVO6";
  case MAV_COMP_ID_SERVO7:
    return "MAV_COMP_ID_SERVO7";
  case MAV_COMP_ID_SERVO8:
    return "MAV_COMP_ID_SERVO8";
  case MAV_COMP_ID_SERVO9:
    return "MAV_COMP_ID_SERVO9";
  case MAV_COMP_ID_SERVO10:
    return "MAV_COMP_ID_SERVO10";
  case MAV_COMP_ID_SERVO11:
    return "MAV_COMP_ID_SERVO11";
  case MAV_COMP_ID_SERVO12:
    return "MAV_COMP_ID_SERVO12";
  case MAV_COMP_ID_SERVO13:
    return "MAV_COMP_ID_SERVO13";
  case MAV_COMP_ID_SERVO14:
    return "MAV_COMP_ID_SERVO14";
  case MAV_COMP_ID_GIMBAL:
    return "MAV_COMP_ID_GIMBAL";
  case MAV_COMP_ID_LOG:
    return "MAV_COMP_ID_LOG";
  case MAV_COMP_ID_ADSB:
    return "MAV_COMP_ID_ADSB";
  case MAV_COMP_ID_OSD:
    return "MAV_COMP_ID_OSD";
  case MAV_COMP_ID_PERIPHERAL:
    return "MAV_COMP_ID_PERIPHERAL";
  case MAV_COMP_ID_QX1_GIMBAL:
    return "MAV_COMP_ID_QX1_GIMBAL";
  case MAV_COMP_ID_FLARM:
    return "MAV_COMP_ID_FLARM";
  case MAV_COMP_ID_MISSIONPLANNER:
    return "MAV_COMP_ID_MISSIONPLANNER";
  case MAV_COMP_ID_PATHPLANNER:
    return "MAV_COMP_ID_PATHPLANNER";
  case MAV_COMP_ID_OBSTACLE_AVOIDANCE:
    return "MAV_COMP_ID_OBSTACLE_AVOIDANCE";
  case MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY:
    return "MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY";
  case MAV_COMP_ID_IMU:
    return "MAV_COMP_ID_IMU";
  case MAV_COMP_ID_IMU_2:
    return "MAV_COMP_ID_IMU_2";
  case MAV_COMP_ID_IMU_3:
    return "MAV_COMP_ID_IMU_3";
  case MAV_COMP_ID_GPS:
    return "MAV_COMP_ID_GPS";
  case MAV_COMP_ID_GPS2:
    return "MAV_COMP_ID_GPS2";
  case MAV_COMP_ID_UDP_BRIDGE:
    return "MAV_COMP_ID_UDP_BRIDGE";
  case MAV_COMP_ID_UART_BRIDGE:
    return "MAV_COMP_ID_UART_BRIDGE";
  case MAV_COMP_ID_SYSTEM_CONTROL:
    return "MAV_COMP_ID_SYSTEM_CONTROL";
  }
  return NULL;
};

static size_t psnprint_MAV_COMPONENT(char **p, size_t *sz,
                                     enum MAV_COMPONENT val) {
  const char *s = MAV_COMPONENT_str(val);
  if (s) {
    return psnprintf(p, sz, "%s", s);
  }
  return psnprintf(p, sz, "MAV_COMPONENT<%d>", (int)val);
}

size_t minimal_message_snprintf(char *buf, size_t size,
                                const struct minimal_message *msg) {
  size_t r = 0;
  switch (msg->msg_id) {

  case MINIMAL_MESSAGE_HEARTBEAT:

    r += psnprintf(&buf, &size, "HEARTBEAT<");

    r += psnprintf(&buf, &size, " custom_mode:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " type:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " autopilot:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " base_mode:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " system_status:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " mavlink_version:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " >");
    break;
  };

  return r;
}
