// Generated enums and structures for Mavlink dialect minimal #0 version 3
// Generated by gomavlink, DO NOT EDIT.

#include "minimal.h"

// Internal function used by both serialisation and deserialisation.
uint8_t minimal_crcextra(enum MINIMAL_MESSAGE mid) {
  switch (mid) {
  case MINIMAL_MESSAGE_HEARTBEAT:
    return 50;
  }
  return 0;
}
