// Generated enums and structures for Mavlink dialect python_array_test #0
// version 3 Generated by gomavlink, DO NOT EDIT.

#include <assert.h>
#include <string.h>

#include "python_array_test.h"

// defined in python_array_test_crc.h
uint8_t python_array_test_crcextra(enum PYTHON_ARRAY_TEST_MESSAGE mid);

inline static uint8_t read_byte(const uint8_t **p) { return *(*p)++; }
inline static int8_t read_int8(const uint8_t **p) { return *(*p)++; }
inline static int16_t read_int16(const uint8_t **p) {
  int16_t r = *(*p)++;
  r |= *(*p)++ << 8;
  return r;
}
inline static uint16_t read_uint16(const uint8_t **p) {
  uint16_t r = *(*p)++;
  r |= *(*p)++ << 8;
  return r;
}
inline static int32_t read_int32(const uint8_t **p) {
  int32_t r = *(*p)++;
  r |= *(*p)++ << 8;
  r |= *(*p)++ << 16;
  r |= *(*p)++ << 24;
  return r;
}
inline static uint32_t read_uint32(const uint8_t **p) {
  uint32_t r = *(*p)++;
  r |= *(*p)++ << 8;
  r |= *(*p)++ << 16;
  r |= *(*p)++ << 24;
  return r;
}
inline static int64_t read_int64(const uint8_t **p) {
  int64_t r = read_uint32(p);
  r |= ((int64_t)read_int32(p)) << 32;
  return r;
}
inline static uint64_t read_uint64(const uint8_t **p) {
  uint64_t r = read_uint32(p);
  r |= ((uint64_t)read_uint32(p)) << 32;
  return r;
}

inline static float read_float32(const uint8_t **p) {
  uint32_t v = read_uint32(p);
  return *(float *)&v;
}
inline static double read_float64(const uint8_t **p) {
  uint64_t v = read_uint64(p);
  return *(double *)&v;
}

inline static uint16_t x25(uint16_t crc, uint8_t v) {
  v ^= crc;
  v ^= v << 4;
  return (crc >> 8) ^ (v << 8) ^ (v << 3) ^
         (v >> 4); // (uint8_t << int) is promoted to int (!!)
}

static void read_payload_base(const uint8_t **p,
                              struct python_array_test_message *msg) {
  switch (msg->msg_id) {

  case PYTHON_ARRAY_TEST_MESSAGE_HEARTBEAT:
    msg->heartbeat.custom_mode = read_uint32(p);
    msg->heartbeat.type = read_byte(p);
    msg->heartbeat.autopilot = read_byte(p);
    msg->heartbeat.base_mode = read_byte(p);
    msg->heartbeat.system_status = read_byte(p);
    msg->heartbeat.mavlink_version = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SYS_STATUS:
    msg->sys_status.onboard_control_sensors_present = read_uint32(p);
    msg->sys_status.onboard_control_sensors_enabled = read_uint32(p);
    msg->sys_status.onboard_control_sensors_health = read_uint32(p);
    msg->sys_status.load = read_uint16(p);
    msg->sys_status.voltage_battery = read_uint16(p);
    msg->sys_status.current_battery = read_int16(p);
    msg->sys_status.drop_rate_comm = read_uint16(p);
    msg->sys_status.errors_comm = read_uint16(p);
    msg->sys_status.errors_count1 = read_uint16(p);
    msg->sys_status.errors_count2 = read_uint16(p);
    msg->sys_status.errors_count3 = read_uint16(p);
    msg->sys_status.errors_count4 = read_uint16(p);
    msg->sys_status.battery_remaining = read_int8(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SYSTEM_TIME:
    msg->system_time.time_unix_usec = read_uint64(p);
    msg->system_time.time_boot_ms = read_uint32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PING:
    msg->ping.time_usec = read_uint64(p);
    msg->ping.seq = read_uint32(p);
    msg->ping.target_system = read_byte(p);
    msg->ping.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CHANGE_OPERATOR_CONTROL:
    msg->change_operator_control.target_system = read_byte(p);
    msg->change_operator_control.control_request = read_byte(p);
    msg->change_operator_control.version = read_byte(p);
    for (size_t i = 0; i < 25; i++)
      msg->change_operator_control.passkey[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CHANGE_OPERATOR_CONTROL_ACK:
    msg->change_operator_control_ack.gcs_system_id = read_byte(p);
    msg->change_operator_control_ack.control_request = read_byte(p);
    msg->change_operator_control_ack.ack = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_AUTH_KEY:

    for (size_t i = 0; i < 32; i++)
      msg->auth_key.key[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LINK_NODE_STATUS:
    msg->link_node_status.timestamp = read_uint64(p);
    msg->link_node_status.tx_rate = read_uint32(p);
    msg->link_node_status.rx_rate = read_uint32(p);
    msg->link_node_status.messages_sent = read_uint32(p);
    msg->link_node_status.messages_received = read_uint32(p);
    msg->link_node_status.messages_lost = read_uint32(p);
    msg->link_node_status.rx_parse_err = read_uint16(p);
    msg->link_node_status.tx_overflows = read_uint16(p);
    msg->link_node_status.rx_overflows = read_uint16(p);
    msg->link_node_status.tx_buf = read_byte(p);
    msg->link_node_status.rx_buf = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_MODE:
    msg->set_mode.custom_mode = read_uint32(p);
    msg->set_mode.target_system = read_byte(p);
    msg->set_mode.base_mode = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_REQUEST_READ:
    msg->param_request_read.param_index = read_int16(p);
    msg->param_request_read.target_system = read_byte(p);
    msg->param_request_read.target_component = read_byte(p);
    for (size_t i = 0; i < 16; i++)
      msg->param_request_read.param_id[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_REQUEST_LIST:
    msg->param_request_list.target_system = read_byte(p);
    msg->param_request_list.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_VALUE:
    msg->param_value.param_value = read_float32(p);
    msg->param_value.param_count = read_uint16(p);
    msg->param_value.param_index = read_uint16(p);
    for (size_t i = 0; i < 16; i++)
      msg->param_value.param_id[i] = read_byte(p);
    msg->param_value.param_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_SET:
    msg->param_set.param_value = read_float32(p);
    msg->param_set.target_system = read_byte(p);
    msg->param_set.target_component = read_byte(p);
    for (size_t i = 0; i < 16; i++)
      msg->param_set.param_id[i] = read_byte(p);
    msg->param_set.param_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_RAW_INT:
    msg->gps_raw_int.time_usec = read_uint64(p);
    msg->gps_raw_int.lat = read_int32(p);
    msg->gps_raw_int.lon = read_int32(p);
    msg->gps_raw_int.alt = read_int32(p);
    msg->gps_raw_int.eph = read_uint16(p);
    msg->gps_raw_int.epv = read_uint16(p);
    msg->gps_raw_int.vel = read_uint16(p);
    msg->gps_raw_int.cog = read_uint16(p);
    msg->gps_raw_int.fix_type = read_byte(p);
    msg->gps_raw_int.satellites_visible = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_STATUS:
    msg->gps_status.satellites_visible = read_byte(p);
    for (size_t i = 0; i < 20; i++)
      msg->gps_status.satellite_prn[i] = read_byte(p);
    for (size_t i = 0; i < 20; i++)
      msg->gps_status.satellite_used[i] = read_byte(p);
    for (size_t i = 0; i < 20; i++)
      msg->gps_status.satellite_elevation[i] = read_byte(p);
    for (size_t i = 0; i < 20; i++)
      msg->gps_status.satellite_azimuth[i] = read_byte(p);
    for (size_t i = 0; i < 20; i++)
      msg->gps_status.satellite_snr[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SCALED_IMU:
    msg->scaled_imu.time_boot_ms = read_uint32(p);
    msg->scaled_imu.xacc = read_int16(p);
    msg->scaled_imu.yacc = read_int16(p);
    msg->scaled_imu.zacc = read_int16(p);
    msg->scaled_imu.xgyro = read_int16(p);
    msg->scaled_imu.ygyro = read_int16(p);
    msg->scaled_imu.zgyro = read_int16(p);
    msg->scaled_imu.xmag = read_int16(p);
    msg->scaled_imu.ymag = read_int16(p);
    msg->scaled_imu.zmag = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RAW_IMU:
    msg->raw_imu.time_usec = read_uint64(p);
    msg->raw_imu.xacc = read_int16(p);
    msg->raw_imu.yacc = read_int16(p);
    msg->raw_imu.zacc = read_int16(p);
    msg->raw_imu.xgyro = read_int16(p);
    msg->raw_imu.ygyro = read_int16(p);
    msg->raw_imu.zgyro = read_int16(p);
    msg->raw_imu.xmag = read_int16(p);
    msg->raw_imu.ymag = read_int16(p);
    msg->raw_imu.zmag = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RAW_PRESSURE:
    msg->raw_pressure.time_usec = read_uint64(p);
    msg->raw_pressure.press_abs = read_int16(p);
    msg->raw_pressure.press_diff1 = read_int16(p);
    msg->raw_pressure.press_diff2 = read_int16(p);
    msg->raw_pressure.temperature = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SCALED_PRESSURE:
    msg->scaled_pressure.time_boot_ms = read_uint32(p);
    msg->scaled_pressure.press_abs = read_float32(p);
    msg->scaled_pressure.press_diff = read_float32(p);
    msg->scaled_pressure.temperature = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ATTITUDE:
    msg->attitude.time_boot_ms = read_uint32(p);
    msg->attitude.roll = read_float32(p);
    msg->attitude.pitch = read_float32(p);
    msg->attitude.yaw = read_float32(p);
    msg->attitude.rollspeed = read_float32(p);
    msg->attitude.pitchspeed = read_float32(p);
    msg->attitude.yawspeed = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ATTITUDE_QUATERNION:
    msg->attitude_quaternion.time_boot_ms = read_uint32(p);
    msg->attitude_quaternion.q1 = read_float32(p);
    msg->attitude_quaternion.q2 = read_float32(p);
    msg->attitude_quaternion.q3 = read_float32(p);
    msg->attitude_quaternion.q4 = read_float32(p);
    msg->attitude_quaternion.rollspeed = read_float32(p);
    msg->attitude_quaternion.pitchspeed = read_float32(p);
    msg->attitude_quaternion.yawspeed = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOCAL_POSITION_NED:
    msg->local_position_ned.time_boot_ms = read_uint32(p);
    msg->local_position_ned.x = read_float32(p);
    msg->local_position_ned.y = read_float32(p);
    msg->local_position_ned.z = read_float32(p);
    msg->local_position_ned.vx = read_float32(p);
    msg->local_position_ned.vy = read_float32(p);
    msg->local_position_ned.vz = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GLOBAL_POSITION_INT:
    msg->global_position_int.time_boot_ms = read_uint32(p);
    msg->global_position_int.lat = read_int32(p);
    msg->global_position_int.lon = read_int32(p);
    msg->global_position_int.alt = read_int32(p);
    msg->global_position_int.relative_alt = read_int32(p);
    msg->global_position_int.vx = read_int16(p);
    msg->global_position_int.vy = read_int16(p);
    msg->global_position_int.vz = read_int16(p);
    msg->global_position_int.hdg = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RC_CHANNELS_SCALED:
    msg->rc_channels_scaled.time_boot_ms = read_uint32(p);
    msg->rc_channels_scaled.chan1_scaled = read_int16(p);
    msg->rc_channels_scaled.chan2_scaled = read_int16(p);
    msg->rc_channels_scaled.chan3_scaled = read_int16(p);
    msg->rc_channels_scaled.chan4_scaled = read_int16(p);
    msg->rc_channels_scaled.chan5_scaled = read_int16(p);
    msg->rc_channels_scaled.chan6_scaled = read_int16(p);
    msg->rc_channels_scaled.chan7_scaled = read_int16(p);
    msg->rc_channels_scaled.chan8_scaled = read_int16(p);
    msg->rc_channels_scaled.port = read_byte(p);
    msg->rc_channels_scaled.rssi = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RC_CHANNELS_RAW:
    msg->rc_channels_raw.time_boot_ms = read_uint32(p);
    msg->rc_channels_raw.chan1_raw = read_uint16(p);
    msg->rc_channels_raw.chan2_raw = read_uint16(p);
    msg->rc_channels_raw.chan3_raw = read_uint16(p);
    msg->rc_channels_raw.chan4_raw = read_uint16(p);
    msg->rc_channels_raw.chan5_raw = read_uint16(p);
    msg->rc_channels_raw.chan6_raw = read_uint16(p);
    msg->rc_channels_raw.chan7_raw = read_uint16(p);
    msg->rc_channels_raw.chan8_raw = read_uint16(p);
    msg->rc_channels_raw.port = read_byte(p);
    msg->rc_channels_raw.rssi = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SERVO_OUTPUT_RAW:
    msg->servo_output_raw.time_usec = read_uint32(p);
    msg->servo_output_raw.servo1_raw = read_uint16(p);
    msg->servo_output_raw.servo2_raw = read_uint16(p);
    msg->servo_output_raw.servo3_raw = read_uint16(p);
    msg->servo_output_raw.servo4_raw = read_uint16(p);
    msg->servo_output_raw.servo5_raw = read_uint16(p);
    msg->servo_output_raw.servo6_raw = read_uint16(p);
    msg->servo_output_raw.servo7_raw = read_uint16(p);
    msg->servo_output_raw.servo8_raw = read_uint16(p);
    msg->servo_output_raw.port = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST_PARTIAL_LIST:
    msg->mission_request_partial_list.start_index = read_int16(p);
    msg->mission_request_partial_list.end_index = read_int16(p);
    msg->mission_request_partial_list.target_system = read_byte(p);
    msg->mission_request_partial_list.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_WRITE_PARTIAL_LIST:
    msg->mission_write_partial_list.start_index = read_int16(p);
    msg->mission_write_partial_list.end_index = read_int16(p);
    msg->mission_write_partial_list.target_system = read_byte(p);
    msg->mission_write_partial_list.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_ITEM:
    msg->mission_item.param1 = read_float32(p);
    msg->mission_item.param2 = read_float32(p);
    msg->mission_item.param3 = read_float32(p);
    msg->mission_item.param4 = read_float32(p);
    msg->mission_item.x = read_float32(p);
    msg->mission_item.y = read_float32(p);
    msg->mission_item.z = read_float32(p);
    msg->mission_item.seq = read_uint16(p);
    msg->mission_item.command = read_uint16(p);
    msg->mission_item.target_system = read_byte(p);
    msg->mission_item.target_component = read_byte(p);
    msg->mission_item.frame = read_byte(p);
    msg->mission_item.current = read_byte(p);
    msg->mission_item.autocontinue = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST:
    msg->mission_request.seq = read_uint16(p);
    msg->mission_request.target_system = read_byte(p);
    msg->mission_request.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_SET_CURRENT:
    msg->mission_set_current.seq = read_uint16(p);
    msg->mission_set_current.target_system = read_byte(p);
    msg->mission_set_current.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_CURRENT:
    msg->mission_current.seq = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST_LIST:
    msg->mission_request_list.target_system = read_byte(p);
    msg->mission_request_list.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_COUNT:
    msg->mission_count.count = read_uint16(p);
    msg->mission_count.target_system = read_byte(p);
    msg->mission_count.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_CLEAR_ALL:
    msg->mission_clear_all.target_system = read_byte(p);
    msg->mission_clear_all.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_ITEM_REACHED:
    msg->mission_item_reached.seq = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_ACK:
    msg->mission_ack.target_system = read_byte(p);
    msg->mission_ack.target_component = read_byte(p);
    msg->mission_ack.type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_GPS_GLOBAL_ORIGIN:
    msg->set_gps_global_origin.latitude = read_int32(p);
    msg->set_gps_global_origin.longitude = read_int32(p);
    msg->set_gps_global_origin.altitude = read_int32(p);
    msg->set_gps_global_origin.target_system = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_GLOBAL_ORIGIN:
    msg->gps_global_origin.latitude = read_int32(p);
    msg->gps_global_origin.longitude = read_int32(p);
    msg->gps_global_origin.altitude = read_int32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_MAP_RC:
    msg->param_map_rc.param_value0 = read_float32(p);
    msg->param_map_rc.scale = read_float32(p);
    msg->param_map_rc.param_value_min = read_float32(p);
    msg->param_map_rc.param_value_max = read_float32(p);
    msg->param_map_rc.param_index = read_int16(p);
    msg->param_map_rc.target_system = read_byte(p);
    msg->param_map_rc.target_component = read_byte(p);
    for (size_t i = 0; i < 16; i++)
      msg->param_map_rc.param_id[i] = read_byte(p);
    msg->param_map_rc.parameter_rc_channel_index = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST_INT:
    msg->mission_request_int.seq = read_uint16(p);
    msg->mission_request_int.target_system = read_byte(p);
    msg->mission_request_int.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_CHANGED:
    msg->mission_changed.start_index = read_int16(p);
    msg->mission_changed.end_index = read_int16(p);
    msg->mission_changed.origin_sysid = read_byte(p);
    msg->mission_changed.origin_compid = read_byte(p);
    msg->mission_changed.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SAFETY_SET_ALLOWED_AREA:
    msg->safety_set_allowed_area.p1x = read_float32(p);
    msg->safety_set_allowed_area.p1y = read_float32(p);
    msg->safety_set_allowed_area.p1z = read_float32(p);
    msg->safety_set_allowed_area.p2x = read_float32(p);
    msg->safety_set_allowed_area.p2y = read_float32(p);
    msg->safety_set_allowed_area.p2z = read_float32(p);
    msg->safety_set_allowed_area.target_system = read_byte(p);
    msg->safety_set_allowed_area.target_component = read_byte(p);
    msg->safety_set_allowed_area.frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SAFETY_ALLOWED_AREA:
    msg->safety_allowed_area.p1x = read_float32(p);
    msg->safety_allowed_area.p1y = read_float32(p);
    msg->safety_allowed_area.p1z = read_float32(p);
    msg->safety_allowed_area.p2x = read_float32(p);
    msg->safety_allowed_area.p2y = read_float32(p);
    msg->safety_allowed_area.p2z = read_float32(p);
    msg->safety_allowed_area.frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ATTITUDE_QUATERNION_COV:
    msg->attitude_quaternion_cov.time_usec = read_uint64(p);
    for (size_t i = 0; i < 4; i++)
      msg->attitude_quaternion_cov.q[i] = read_float32(p);
    msg->attitude_quaternion_cov.rollspeed = read_float32(p);
    msg->attitude_quaternion_cov.pitchspeed = read_float32(p);
    msg->attitude_quaternion_cov.yawspeed = read_float32(p);
    for (size_t i = 0; i < 9; i++)
      msg->attitude_quaternion_cov.covariance[i] = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_NAV_CONTROLLER_OUTPUT:
    msg->nav_controller_output.nav_roll = read_float32(p);
    msg->nav_controller_output.nav_pitch = read_float32(p);
    msg->nav_controller_output.alt_error = read_float32(p);
    msg->nav_controller_output.aspd_error = read_float32(p);
    msg->nav_controller_output.xtrack_error = read_float32(p);
    msg->nav_controller_output.nav_bearing = read_int16(p);
    msg->nav_controller_output.target_bearing = read_int16(p);
    msg->nav_controller_output.wp_dist = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GLOBAL_POSITION_INT_COV:
    msg->global_position_int_cov.time_usec = read_uint64(p);
    msg->global_position_int_cov.lat = read_int32(p);
    msg->global_position_int_cov.lon = read_int32(p);
    msg->global_position_int_cov.alt = read_int32(p);
    msg->global_position_int_cov.relative_alt = read_int32(p);
    msg->global_position_int_cov.vx = read_float32(p);
    msg->global_position_int_cov.vy = read_float32(p);
    msg->global_position_int_cov.vz = read_float32(p);
    for (size_t i = 0; i < 36; i++)
      msg->global_position_int_cov.covariance[i] = read_float32(p);
    msg->global_position_int_cov.estimator_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOCAL_POSITION_NED_COV:
    msg->local_position_ned_cov.time_usec = read_uint64(p);
    msg->local_position_ned_cov.x = read_float32(p);
    msg->local_position_ned_cov.y = read_float32(p);
    msg->local_position_ned_cov.z = read_float32(p);
    msg->local_position_ned_cov.vx = read_float32(p);
    msg->local_position_ned_cov.vy = read_float32(p);
    msg->local_position_ned_cov.vz = read_float32(p);
    msg->local_position_ned_cov.ax = read_float32(p);
    msg->local_position_ned_cov.ay = read_float32(p);
    msg->local_position_ned_cov.az = read_float32(p);
    for (size_t i = 0; i < 45; i++)
      msg->local_position_ned_cov.covariance[i] = read_float32(p);
    msg->local_position_ned_cov.estimator_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RC_CHANNELS:
    msg->rc_channels.time_boot_ms = read_uint32(p);
    msg->rc_channels.chan1_raw = read_uint16(p);
    msg->rc_channels.chan2_raw = read_uint16(p);
    msg->rc_channels.chan3_raw = read_uint16(p);
    msg->rc_channels.chan4_raw = read_uint16(p);
    msg->rc_channels.chan5_raw = read_uint16(p);
    msg->rc_channels.chan6_raw = read_uint16(p);
    msg->rc_channels.chan7_raw = read_uint16(p);
    msg->rc_channels.chan8_raw = read_uint16(p);
    msg->rc_channels.chan9_raw = read_uint16(p);
    msg->rc_channels.chan10_raw = read_uint16(p);
    msg->rc_channels.chan11_raw = read_uint16(p);
    msg->rc_channels.chan12_raw = read_uint16(p);
    msg->rc_channels.chan13_raw = read_uint16(p);
    msg->rc_channels.chan14_raw = read_uint16(p);
    msg->rc_channels.chan15_raw = read_uint16(p);
    msg->rc_channels.chan16_raw = read_uint16(p);
    msg->rc_channels.chan17_raw = read_uint16(p);
    msg->rc_channels.chan18_raw = read_uint16(p);
    msg->rc_channels.chancount = read_byte(p);
    msg->rc_channels.rssi = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_REQUEST_DATA_STREAM:
    msg->request_data_stream.req_message_rate = read_uint16(p);
    msg->request_data_stream.target_system = read_byte(p);
    msg->request_data_stream.target_component = read_byte(p);
    msg->request_data_stream.req_stream_id = read_byte(p);
    msg->request_data_stream.start_stop = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DATA_STREAM:
    msg->data_stream.message_rate = read_uint16(p);
    msg->data_stream.stream_id = read_byte(p);
    msg->data_stream.on_off = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MANUAL_CONTROL:
    msg->manual_control.x = read_int16(p);
    msg->manual_control.y = read_int16(p);
    msg->manual_control.z = read_int16(p);
    msg->manual_control.r = read_int16(p);
    msg->manual_control.buttons = read_uint16(p);
    msg->manual_control.target = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RC_CHANNELS_OVERRIDE:
    msg->rc_channels_override.chan1_raw = read_uint16(p);
    msg->rc_channels_override.chan2_raw = read_uint16(p);
    msg->rc_channels_override.chan3_raw = read_uint16(p);
    msg->rc_channels_override.chan4_raw = read_uint16(p);
    msg->rc_channels_override.chan5_raw = read_uint16(p);
    msg->rc_channels_override.chan6_raw = read_uint16(p);
    msg->rc_channels_override.chan7_raw = read_uint16(p);
    msg->rc_channels_override.chan8_raw = read_uint16(p);
    msg->rc_channels_override.target_system = read_byte(p);
    msg->rc_channels_override.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_ITEM_INT:
    msg->mission_item_int.param1 = read_float32(p);
    msg->mission_item_int.param2 = read_float32(p);
    msg->mission_item_int.param3 = read_float32(p);
    msg->mission_item_int.param4 = read_float32(p);
    msg->mission_item_int.x = read_int32(p);
    msg->mission_item_int.y = read_int32(p);
    msg->mission_item_int.z = read_float32(p);
    msg->mission_item_int.seq = read_uint16(p);
    msg->mission_item_int.command = read_uint16(p);
    msg->mission_item_int.target_system = read_byte(p);
    msg->mission_item_int.target_component = read_byte(p);
    msg->mission_item_int.frame = read_byte(p);
    msg->mission_item_int.current = read_byte(p);
    msg->mission_item_int.autocontinue = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VFR_HUD:
    msg->vfr_hud.airspeed = read_float32(p);
    msg->vfr_hud.groundspeed = read_float32(p);
    msg->vfr_hud.alt = read_float32(p);
    msg->vfr_hud.climb = read_float32(p);
    msg->vfr_hud.heading = read_int16(p);
    msg->vfr_hud.throttle = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_COMMAND_INT:
    msg->command_int.param1 = read_float32(p);
    msg->command_int.param2 = read_float32(p);
    msg->command_int.param3 = read_float32(p);
    msg->command_int.param4 = read_float32(p);
    msg->command_int.x = read_int32(p);
    msg->command_int.y = read_int32(p);
    msg->command_int.z = read_float32(p);
    msg->command_int.command = read_uint16(p);
    msg->command_int.target_system = read_byte(p);
    msg->command_int.target_component = read_byte(p);
    msg->command_int.frame = read_byte(p);
    msg->command_int.current = read_byte(p);
    msg->command_int.autocontinue = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_COMMAND_LONG:
    msg->command_long.param1 = read_float32(p);
    msg->command_long.param2 = read_float32(p);
    msg->command_long.param3 = read_float32(p);
    msg->command_long.param4 = read_float32(p);
    msg->command_long.param5 = read_float32(p);
    msg->command_long.param6 = read_float32(p);
    msg->command_long.param7 = read_float32(p);
    msg->command_long.command = read_uint16(p);
    msg->command_long.target_system = read_byte(p);
    msg->command_long.target_component = read_byte(p);
    msg->command_long.confirmation = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_COMMAND_ACK:
    msg->command_ack.command = read_uint16(p);
    msg->command_ack.result = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MANUAL_SETPOINT:
    msg->manual_setpoint.time_boot_ms = read_uint32(p);
    msg->manual_setpoint.roll = read_float32(p);
    msg->manual_setpoint.pitch = read_float32(p);
    msg->manual_setpoint.yaw = read_float32(p);
    msg->manual_setpoint.thrust = read_float32(p);
    msg->manual_setpoint.mode_switch = read_byte(p);
    msg->manual_setpoint.manual_override_switch = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_ATTITUDE_TARGET:
    msg->set_attitude_target.time_boot_ms = read_uint32(p);
    for (size_t i = 0; i < 4; i++)
      msg->set_attitude_target.q[i] = read_float32(p);
    msg->set_attitude_target.body_roll_rate = read_float32(p);
    msg->set_attitude_target.body_pitch_rate = read_float32(p);
    msg->set_attitude_target.body_yaw_rate = read_float32(p);
    msg->set_attitude_target.thrust = read_float32(p);
    msg->set_attitude_target.target_system = read_byte(p);
    msg->set_attitude_target.target_component = read_byte(p);
    msg->set_attitude_target.type_mask = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ATTITUDE_TARGET:
    msg->attitude_target.time_boot_ms = read_uint32(p);
    for (size_t i = 0; i < 4; i++)
      msg->attitude_target.q[i] = read_float32(p);
    msg->attitude_target.body_roll_rate = read_float32(p);
    msg->attitude_target.body_pitch_rate = read_float32(p);
    msg->attitude_target.body_yaw_rate = read_float32(p);
    msg->attitude_target.thrust = read_float32(p);
    msg->attitude_target.type_mask = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_POSITION_TARGET_LOCAL_NED:
    msg->set_position_target_local_ned.time_boot_ms = read_uint32(p);
    msg->set_position_target_local_ned.x = read_float32(p);
    msg->set_position_target_local_ned.y = read_float32(p);
    msg->set_position_target_local_ned.z = read_float32(p);
    msg->set_position_target_local_ned.vx = read_float32(p);
    msg->set_position_target_local_ned.vy = read_float32(p);
    msg->set_position_target_local_ned.vz = read_float32(p);
    msg->set_position_target_local_ned.afx = read_float32(p);
    msg->set_position_target_local_ned.afy = read_float32(p);
    msg->set_position_target_local_ned.afz = read_float32(p);
    msg->set_position_target_local_ned.yaw = read_float32(p);
    msg->set_position_target_local_ned.yaw_rate = read_float32(p);
    msg->set_position_target_local_ned.type_mask = read_uint16(p);
    msg->set_position_target_local_ned.target_system = read_byte(p);
    msg->set_position_target_local_ned.target_component = read_byte(p);
    msg->set_position_target_local_ned.coordinate_frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_POSITION_TARGET_LOCAL_NED:
    msg->position_target_local_ned.time_boot_ms = read_uint32(p);
    msg->position_target_local_ned.x = read_float32(p);
    msg->position_target_local_ned.y = read_float32(p);
    msg->position_target_local_ned.z = read_float32(p);
    msg->position_target_local_ned.vx = read_float32(p);
    msg->position_target_local_ned.vy = read_float32(p);
    msg->position_target_local_ned.vz = read_float32(p);
    msg->position_target_local_ned.afx = read_float32(p);
    msg->position_target_local_ned.afy = read_float32(p);
    msg->position_target_local_ned.afz = read_float32(p);
    msg->position_target_local_ned.yaw = read_float32(p);
    msg->position_target_local_ned.yaw_rate = read_float32(p);
    msg->position_target_local_ned.type_mask = read_uint16(p);
    msg->position_target_local_ned.coordinate_frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_POSITION_TARGET_GLOBAL_INT:
    msg->set_position_target_global_int.time_boot_ms = read_uint32(p);
    msg->set_position_target_global_int.lat_int = read_int32(p);
    msg->set_position_target_global_int.lon_int = read_int32(p);
    msg->set_position_target_global_int.alt = read_float32(p);
    msg->set_position_target_global_int.vx = read_float32(p);
    msg->set_position_target_global_int.vy = read_float32(p);
    msg->set_position_target_global_int.vz = read_float32(p);
    msg->set_position_target_global_int.afx = read_float32(p);
    msg->set_position_target_global_int.afy = read_float32(p);
    msg->set_position_target_global_int.afz = read_float32(p);
    msg->set_position_target_global_int.yaw = read_float32(p);
    msg->set_position_target_global_int.yaw_rate = read_float32(p);
    msg->set_position_target_global_int.type_mask = read_uint16(p);
    msg->set_position_target_global_int.target_system = read_byte(p);
    msg->set_position_target_global_int.target_component = read_byte(p);
    msg->set_position_target_global_int.coordinate_frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_POSITION_TARGET_GLOBAL_INT:
    msg->position_target_global_int.time_boot_ms = read_uint32(p);
    msg->position_target_global_int.lat_int = read_int32(p);
    msg->position_target_global_int.lon_int = read_int32(p);
    msg->position_target_global_int.alt = read_float32(p);
    msg->position_target_global_int.vx = read_float32(p);
    msg->position_target_global_int.vy = read_float32(p);
    msg->position_target_global_int.vz = read_float32(p);
    msg->position_target_global_int.afx = read_float32(p);
    msg->position_target_global_int.afy = read_float32(p);
    msg->position_target_global_int.afz = read_float32(p);
    msg->position_target_global_int.yaw = read_float32(p);
    msg->position_target_global_int.yaw_rate = read_float32(p);
    msg->position_target_global_int.type_mask = read_uint16(p);
    msg->position_target_global_int.coordinate_frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET:
    msg->local_position_ned_system_global_offset.time_boot_ms = read_uint32(p);
    msg->local_position_ned_system_global_offset.x = read_float32(p);
    msg->local_position_ned_system_global_offset.y = read_float32(p);
    msg->local_position_ned_system_global_offset.z = read_float32(p);
    msg->local_position_ned_system_global_offset.roll = read_float32(p);
    msg->local_position_ned_system_global_offset.pitch = read_float32(p);
    msg->local_position_ned_system_global_offset.yaw = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_STATE:
    msg->hil_state.time_usec = read_uint64(p);
    msg->hil_state.roll = read_float32(p);
    msg->hil_state.pitch = read_float32(p);
    msg->hil_state.yaw = read_float32(p);
    msg->hil_state.rollspeed = read_float32(p);
    msg->hil_state.pitchspeed = read_float32(p);
    msg->hil_state.yawspeed = read_float32(p);
    msg->hil_state.lat = read_int32(p);
    msg->hil_state.lon = read_int32(p);
    msg->hil_state.alt = read_int32(p);
    msg->hil_state.vx = read_int16(p);
    msg->hil_state.vy = read_int16(p);
    msg->hil_state.vz = read_int16(p);
    msg->hil_state.xacc = read_int16(p);
    msg->hil_state.yacc = read_int16(p);
    msg->hil_state.zacc = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_CONTROLS:
    msg->hil_controls.time_usec = read_uint64(p);
    msg->hil_controls.roll_ailerons = read_float32(p);
    msg->hil_controls.pitch_elevator = read_float32(p);
    msg->hil_controls.yaw_rudder = read_float32(p);
    msg->hil_controls.throttle = read_float32(p);
    msg->hil_controls.aux1 = read_float32(p);
    msg->hil_controls.aux2 = read_float32(p);
    msg->hil_controls.aux3 = read_float32(p);
    msg->hil_controls.aux4 = read_float32(p);
    msg->hil_controls.mode = read_byte(p);
    msg->hil_controls.nav_mode = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_RC_INPUTS_RAW:
    msg->hil_rc_inputs_raw.time_usec = read_uint64(p);
    msg->hil_rc_inputs_raw.chan1_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan2_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan3_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan4_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan5_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan6_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan7_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan8_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan9_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan10_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan11_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.chan12_raw = read_uint16(p);
    msg->hil_rc_inputs_raw.rssi = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_ACTUATOR_CONTROLS:
    msg->hil_actuator_controls.time_usec = read_uint64(p);
    msg->hil_actuator_controls.flags = read_uint64(p);
    for (size_t i = 0; i < 16; i++)
      msg->hil_actuator_controls.controls[i] = read_float32(p);
    msg->hil_actuator_controls.mode = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_OPTICAL_FLOW:
    msg->optical_flow.time_usec = read_uint64(p);
    msg->optical_flow.flow_comp_m_x = read_float32(p);
    msg->optical_flow.flow_comp_m_y = read_float32(p);
    msg->optical_flow.ground_distance = read_float32(p);
    msg->optical_flow.flow_x = read_int16(p);
    msg->optical_flow.flow_y = read_int16(p);
    msg->optical_flow.sensor_id = read_byte(p);
    msg->optical_flow.quality = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GLOBAL_VISION_POSITION_ESTIMATE:
    msg->global_vision_position_estimate.usec = read_uint64(p);
    msg->global_vision_position_estimate.x = read_float32(p);
    msg->global_vision_position_estimate.y = read_float32(p);
    msg->global_vision_position_estimate.z = read_float32(p);
    msg->global_vision_position_estimate.roll = read_float32(p);
    msg->global_vision_position_estimate.pitch = read_float32(p);
    msg->global_vision_position_estimate.yaw = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VISION_POSITION_ESTIMATE:
    msg->vision_position_estimate.usec = read_uint64(p);
    msg->vision_position_estimate.x = read_float32(p);
    msg->vision_position_estimate.y = read_float32(p);
    msg->vision_position_estimate.z = read_float32(p);
    msg->vision_position_estimate.roll = read_float32(p);
    msg->vision_position_estimate.pitch = read_float32(p);
    msg->vision_position_estimate.yaw = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VISION_SPEED_ESTIMATE:
    msg->vision_speed_estimate.usec = read_uint64(p);
    msg->vision_speed_estimate.x = read_float32(p);
    msg->vision_speed_estimate.y = read_float32(p);
    msg->vision_speed_estimate.z = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VICON_POSITION_ESTIMATE:
    msg->vicon_position_estimate.usec = read_uint64(p);
    msg->vicon_position_estimate.x = read_float32(p);
    msg->vicon_position_estimate.y = read_float32(p);
    msg->vicon_position_estimate.z = read_float32(p);
    msg->vicon_position_estimate.roll = read_float32(p);
    msg->vicon_position_estimate.pitch = read_float32(p);
    msg->vicon_position_estimate.yaw = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIGHRES_IMU:
    msg->highres_imu.time_usec = read_uint64(p);
    msg->highres_imu.xacc = read_float32(p);
    msg->highres_imu.yacc = read_float32(p);
    msg->highres_imu.zacc = read_float32(p);
    msg->highres_imu.xgyro = read_float32(p);
    msg->highres_imu.ygyro = read_float32(p);
    msg->highres_imu.zgyro = read_float32(p);
    msg->highres_imu.xmag = read_float32(p);
    msg->highres_imu.ymag = read_float32(p);
    msg->highres_imu.zmag = read_float32(p);
    msg->highres_imu.abs_pressure = read_float32(p);
    msg->highres_imu.diff_pressure = read_float32(p);
    msg->highres_imu.pressure_alt = read_float32(p);
    msg->highres_imu.temperature = read_float32(p);
    msg->highres_imu.fields_updated = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_OPTICAL_FLOW_RAD:
    msg->optical_flow_rad.time_usec = read_uint64(p);
    msg->optical_flow_rad.integration_time_us = read_uint32(p);
    msg->optical_flow_rad.integrated_x = read_float32(p);
    msg->optical_flow_rad.integrated_y = read_float32(p);
    msg->optical_flow_rad.integrated_xgyro = read_float32(p);
    msg->optical_flow_rad.integrated_ygyro = read_float32(p);
    msg->optical_flow_rad.integrated_zgyro = read_float32(p);
    msg->optical_flow_rad.time_delta_distance_us = read_uint32(p);
    msg->optical_flow_rad.distance = read_float32(p);
    msg->optical_flow_rad.temperature = read_int16(p);
    msg->optical_flow_rad.sensor_id = read_byte(p);
    msg->optical_flow_rad.quality = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_SENSOR:
    msg->hil_sensor.time_usec = read_uint64(p);
    msg->hil_sensor.xacc = read_float32(p);
    msg->hil_sensor.yacc = read_float32(p);
    msg->hil_sensor.zacc = read_float32(p);
    msg->hil_sensor.xgyro = read_float32(p);
    msg->hil_sensor.ygyro = read_float32(p);
    msg->hil_sensor.zgyro = read_float32(p);
    msg->hil_sensor.xmag = read_float32(p);
    msg->hil_sensor.ymag = read_float32(p);
    msg->hil_sensor.zmag = read_float32(p);
    msg->hil_sensor.abs_pressure = read_float32(p);
    msg->hil_sensor.diff_pressure = read_float32(p);
    msg->hil_sensor.pressure_alt = read_float32(p);
    msg->hil_sensor.temperature = read_float32(p);
    msg->hil_sensor.fields_updated = read_uint32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SIM_STATE:
    msg->sim_state.q1 = read_float32(p);
    msg->sim_state.q2 = read_float32(p);
    msg->sim_state.q3 = read_float32(p);
    msg->sim_state.q4 = read_float32(p);
    msg->sim_state.roll = read_float32(p);
    msg->sim_state.pitch = read_float32(p);
    msg->sim_state.yaw = read_float32(p);
    msg->sim_state.xacc = read_float32(p);
    msg->sim_state.yacc = read_float32(p);
    msg->sim_state.zacc = read_float32(p);
    msg->sim_state.xgyro = read_float32(p);
    msg->sim_state.ygyro = read_float32(p);
    msg->sim_state.zgyro = read_float32(p);
    msg->sim_state.lat = read_float32(p);
    msg->sim_state.lon = read_float32(p);
    msg->sim_state.alt = read_float32(p);
    msg->sim_state.std_dev_horz = read_float32(p);
    msg->sim_state.std_dev_vert = read_float32(p);
    msg->sim_state.vn = read_float32(p);
    msg->sim_state.ve = read_float32(p);
    msg->sim_state.vd = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RADIO_STATUS:
    msg->radio_status.rxerrors = read_uint16(p);
    msg->radio_status.fixed = read_uint16(p);
    msg->radio_status.rssi = read_byte(p);
    msg->radio_status.remrssi = read_byte(p);
    msg->radio_status.txbuf = read_byte(p);
    msg->radio_status.noise = read_byte(p);
    msg->radio_status.remnoise = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_FILE_TRANSFER_PROTOCOL:
    msg->file_transfer_protocol.target_network = read_byte(p);
    msg->file_transfer_protocol.target_system = read_byte(p);
    msg->file_transfer_protocol.target_component = read_byte(p);
    for (size_t i = 0; i < 251; i++)
      msg->file_transfer_protocol.payload[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TIMESYNC:
    msg->timesync.tc1 = read_int64(p);
    msg->timesync.ts1 = read_int64(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CAMERA_TRIGGER:
    msg->camera_trigger.time_usec = read_uint64(p);
    msg->camera_trigger.seq = read_uint32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_GPS:
    msg->hil_gps.time_usec = read_uint64(p);
    msg->hil_gps.lat = read_int32(p);
    msg->hil_gps.lon = read_int32(p);
    msg->hil_gps.alt = read_int32(p);
    msg->hil_gps.eph = read_uint16(p);
    msg->hil_gps.epv = read_uint16(p);
    msg->hil_gps.vel = read_uint16(p);
    msg->hil_gps.vn = read_int16(p);
    msg->hil_gps.ve = read_int16(p);
    msg->hil_gps.vd = read_int16(p);
    msg->hil_gps.cog = read_uint16(p);
    msg->hil_gps.fix_type = read_byte(p);
    msg->hil_gps.satellites_visible = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_OPTICAL_FLOW:
    msg->hil_optical_flow.time_usec = read_uint64(p);
    msg->hil_optical_flow.integration_time_us = read_uint32(p);
    msg->hil_optical_flow.integrated_x = read_float32(p);
    msg->hil_optical_flow.integrated_y = read_float32(p);
    msg->hil_optical_flow.integrated_xgyro = read_float32(p);
    msg->hil_optical_flow.integrated_ygyro = read_float32(p);
    msg->hil_optical_flow.integrated_zgyro = read_float32(p);
    msg->hil_optical_flow.time_delta_distance_us = read_uint32(p);
    msg->hil_optical_flow.distance = read_float32(p);
    msg->hil_optical_flow.temperature = read_int16(p);
    msg->hil_optical_flow.sensor_id = read_byte(p);
    msg->hil_optical_flow.quality = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIL_STATE_QUATERNION:
    msg->hil_state_quaternion.time_usec = read_uint64(p);
    for (size_t i = 0; i < 4; i++)
      msg->hil_state_quaternion.attitude_quaternion[i] = read_float32(p);
    msg->hil_state_quaternion.rollspeed = read_float32(p);
    msg->hil_state_quaternion.pitchspeed = read_float32(p);
    msg->hil_state_quaternion.yawspeed = read_float32(p);
    msg->hil_state_quaternion.lat = read_int32(p);
    msg->hil_state_quaternion.lon = read_int32(p);
    msg->hil_state_quaternion.alt = read_int32(p);
    msg->hil_state_quaternion.vx = read_int16(p);
    msg->hil_state_quaternion.vy = read_int16(p);
    msg->hil_state_quaternion.vz = read_int16(p);
    msg->hil_state_quaternion.ind_airspeed = read_uint16(p);
    msg->hil_state_quaternion.true_airspeed = read_uint16(p);
    msg->hil_state_quaternion.xacc = read_int16(p);
    msg->hil_state_quaternion.yacc = read_int16(p);
    msg->hil_state_quaternion.zacc = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SCALED_IMU2:
    msg->scaled_imu2.time_boot_ms = read_uint32(p);
    msg->scaled_imu2.xacc = read_int16(p);
    msg->scaled_imu2.yacc = read_int16(p);
    msg->scaled_imu2.zacc = read_int16(p);
    msg->scaled_imu2.xgyro = read_int16(p);
    msg->scaled_imu2.ygyro = read_int16(p);
    msg->scaled_imu2.zgyro = read_int16(p);
    msg->scaled_imu2.xmag = read_int16(p);
    msg->scaled_imu2.ymag = read_int16(p);
    msg->scaled_imu2.zmag = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOG_REQUEST_LIST:
    msg->log_request_list.start = read_uint16(p);
    msg->log_request_list.end = read_uint16(p);
    msg->log_request_list.target_system = read_byte(p);
    msg->log_request_list.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOG_ENTRY:
    msg->log_entry.time_utc = read_uint32(p);
    msg->log_entry.size = read_uint32(p);
    msg->log_entry.id = read_uint16(p);
    msg->log_entry.num_logs = read_uint16(p);
    msg->log_entry.last_log_num = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOG_REQUEST_DATA:
    msg->log_request_data.ofs = read_uint32(p);
    msg->log_request_data.count = read_uint32(p);
    msg->log_request_data.id = read_uint16(p);
    msg->log_request_data.target_system = read_byte(p);
    msg->log_request_data.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOG_DATA:
    msg->log_data.ofs = read_uint32(p);
    msg->log_data.id = read_uint16(p);
    msg->log_data.count = read_byte(p);
    for (size_t i = 0; i < 90; i++)
      msg->log_data.data[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOG_ERASE:
    msg->log_erase.target_system = read_byte(p);
    msg->log_erase.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOG_REQUEST_END:
    msg->log_request_end.target_system = read_byte(p);
    msg->log_request_end.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_INJECT_DATA:
    msg->gps_inject_data.target_system = read_byte(p);
    msg->gps_inject_data.target_component = read_byte(p);
    msg->gps_inject_data.len = read_byte(p);
    for (size_t i = 0; i < 110; i++)
      msg->gps_inject_data.data[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS2_RAW:
    msg->gps2_raw.time_usec = read_uint64(p);
    msg->gps2_raw.lat = read_int32(p);
    msg->gps2_raw.lon = read_int32(p);
    msg->gps2_raw.alt = read_int32(p);
    msg->gps2_raw.dgps_age = read_uint32(p);
    msg->gps2_raw.eph = read_uint16(p);
    msg->gps2_raw.epv = read_uint16(p);
    msg->gps2_raw.vel = read_uint16(p);
    msg->gps2_raw.cog = read_uint16(p);
    msg->gps2_raw.fix_type = read_byte(p);
    msg->gps2_raw.satellites_visible = read_byte(p);
    msg->gps2_raw.dgps_numch = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_POWER_STATUS:
    msg->power_status.Vcc = read_uint16(p);
    msg->power_status.Vservo = read_uint16(p);
    msg->power_status.flags = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SERIAL_CONTROL:
    msg->serial_control.baudrate = read_uint32(p);
    msg->serial_control.timeout = read_uint16(p);
    msg->serial_control.device = read_byte(p);
    msg->serial_control.flags = read_byte(p);
    msg->serial_control.count = read_byte(p);
    for (size_t i = 0; i < 70; i++)
      msg->serial_control.data[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_RTK:
    msg->gps_rtk.time_last_baseline_ms = read_uint32(p);
    msg->gps_rtk.tow = read_uint32(p);
    msg->gps_rtk.baseline_a_mm = read_int32(p);
    msg->gps_rtk.baseline_b_mm = read_int32(p);
    msg->gps_rtk.baseline_c_mm = read_int32(p);
    msg->gps_rtk.accuracy = read_uint32(p);
    msg->gps_rtk.iar_num_hypotheses = read_int32(p);
    msg->gps_rtk.wn = read_uint16(p);
    msg->gps_rtk.rtk_receiver_id = read_byte(p);
    msg->gps_rtk.rtk_health = read_byte(p);
    msg->gps_rtk.rtk_rate = read_byte(p);
    msg->gps_rtk.nsats = read_byte(p);
    msg->gps_rtk.baseline_coords_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS2_RTK:
    msg->gps2_rtk.time_last_baseline_ms = read_uint32(p);
    msg->gps2_rtk.tow = read_uint32(p);
    msg->gps2_rtk.baseline_a_mm = read_int32(p);
    msg->gps2_rtk.baseline_b_mm = read_int32(p);
    msg->gps2_rtk.baseline_c_mm = read_int32(p);
    msg->gps2_rtk.accuracy = read_uint32(p);
    msg->gps2_rtk.iar_num_hypotheses = read_int32(p);
    msg->gps2_rtk.wn = read_uint16(p);
    msg->gps2_rtk.rtk_receiver_id = read_byte(p);
    msg->gps2_rtk.rtk_health = read_byte(p);
    msg->gps2_rtk.rtk_rate = read_byte(p);
    msg->gps2_rtk.nsats = read_byte(p);
    msg->gps2_rtk.baseline_coords_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SCALED_IMU3:
    msg->scaled_imu3.time_boot_ms = read_uint32(p);
    msg->scaled_imu3.xacc = read_int16(p);
    msg->scaled_imu3.yacc = read_int16(p);
    msg->scaled_imu3.zacc = read_int16(p);
    msg->scaled_imu3.xgyro = read_int16(p);
    msg->scaled_imu3.ygyro = read_int16(p);
    msg->scaled_imu3.zgyro = read_int16(p);
    msg->scaled_imu3.xmag = read_int16(p);
    msg->scaled_imu3.ymag = read_int16(p);
    msg->scaled_imu3.zmag = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DATA_TRANSMISSION_HANDSHAKE:
    msg->data_transmission_handshake.size = read_uint32(p);
    msg->data_transmission_handshake.width = read_uint16(p);
    msg->data_transmission_handshake.height = read_uint16(p);
    msg->data_transmission_handshake.packets = read_uint16(p);
    msg->data_transmission_handshake.type = read_byte(p);
    msg->data_transmission_handshake.payload = read_byte(p);
    msg->data_transmission_handshake.jpg_quality = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ENCAPSULATED_DATA:
    msg->encapsulated_data.seqnr = read_uint16(p);
    for (size_t i = 0; i < 253; i++)
      msg->encapsulated_data.data[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DISTANCE_SENSOR:
    msg->distance_sensor.time_boot_ms = read_uint32(p);
    msg->distance_sensor.min_distance = read_uint16(p);
    msg->distance_sensor.max_distance = read_uint16(p);
    msg->distance_sensor.current_distance = read_uint16(p);
    msg->distance_sensor.type = read_byte(p);
    msg->distance_sensor.id = read_byte(p);
    msg->distance_sensor.orientation = read_byte(p);
    msg->distance_sensor.covariance = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TERRAIN_REQUEST:
    msg->terrain_request.mask = read_uint64(p);
    msg->terrain_request.lat = read_int32(p);
    msg->terrain_request.lon = read_int32(p);
    msg->terrain_request.grid_spacing = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TERRAIN_DATA:
    msg->terrain_data.lat = read_int32(p);
    msg->terrain_data.lon = read_int32(p);
    msg->terrain_data.grid_spacing = read_uint16(p);
    for (size_t i = 0; i < 16; i++)
      msg->terrain_data.data[i] = read_int16(p);
    msg->terrain_data.gridbit = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TERRAIN_CHECK:
    msg->terrain_check.lat = read_int32(p);
    msg->terrain_check.lon = read_int32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TERRAIN_REPORT:
    msg->terrain_report.lat = read_int32(p);
    msg->terrain_report.lon = read_int32(p);
    msg->terrain_report.terrain_height = read_float32(p);
    msg->terrain_report.current_height = read_float32(p);
    msg->terrain_report.spacing = read_uint16(p);
    msg->terrain_report.pending = read_uint16(p);
    msg->terrain_report.loaded = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SCALED_PRESSURE2:
    msg->scaled_pressure2.time_boot_ms = read_uint32(p);
    msg->scaled_pressure2.press_abs = read_float32(p);
    msg->scaled_pressure2.press_diff = read_float32(p);
    msg->scaled_pressure2.temperature = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ATT_POS_MOCAP:
    msg->att_pos_mocap.time_usec = read_uint64(p);
    for (size_t i = 0; i < 4; i++)
      msg->att_pos_mocap.q[i] = read_float32(p);
    msg->att_pos_mocap.x = read_float32(p);
    msg->att_pos_mocap.y = read_float32(p);
    msg->att_pos_mocap.z = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_ACTUATOR_CONTROL_TARGET:
    msg->set_actuator_control_target.time_usec = read_uint64(p);
    for (size_t i = 0; i < 8; i++)
      msg->set_actuator_control_target.controls[i] = read_float32(p);
    msg->set_actuator_control_target.group_mlx = read_byte(p);
    msg->set_actuator_control_target.target_system = read_byte(p);
    msg->set_actuator_control_target.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ACTUATOR_CONTROL_TARGET:
    msg->actuator_control_target.time_usec = read_uint64(p);
    for (size_t i = 0; i < 8; i++)
      msg->actuator_control_target.controls[i] = read_float32(p);
    msg->actuator_control_target.group_mlx = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ALTITUDE:
    msg->altitude.time_usec = read_uint64(p);
    msg->altitude.altitude_monotonic = read_float32(p);
    msg->altitude.altitude_amsl = read_float32(p);
    msg->altitude.altitude_local = read_float32(p);
    msg->altitude.altitude_relative = read_float32(p);
    msg->altitude.altitude_terrain = read_float32(p);
    msg->altitude.bottom_clearance = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RESOURCE_REQUEST:
    msg->resource_request.request_id = read_byte(p);
    msg->resource_request.uri_type = read_byte(p);
    for (size_t i = 0; i < 120; i++)
      msg->resource_request.uri[i] = read_byte(p);
    msg->resource_request.transfer_type = read_byte(p);
    for (size_t i = 0; i < 120; i++)
      msg->resource_request.storage[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SCALED_PRESSURE3:
    msg->scaled_pressure3.time_boot_ms = read_uint32(p);
    msg->scaled_pressure3.press_abs = read_float32(p);
    msg->scaled_pressure3.press_diff = read_float32(p);
    msg->scaled_pressure3.temperature = read_int16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_FOLLOW_TARGET:
    msg->follow_target.timestamp = read_uint64(p);
    msg->follow_target.custom_state = read_uint64(p);
    msg->follow_target.lat = read_int32(p);
    msg->follow_target.lon = read_int32(p);
    msg->follow_target.alt = read_float32(p);
    for (size_t i = 0; i < 3; i++)
      msg->follow_target.vel[i] = read_float32(p);
    for (size_t i = 0; i < 3; i++)
      msg->follow_target.acc[i] = read_float32(p);
    for (size_t i = 0; i < 4; i++)
      msg->follow_target.attitude_q[i] = read_float32(p);
    for (size_t i = 0; i < 3; i++)
      msg->follow_target.rates[i] = read_float32(p);
    for (size_t i = 0; i < 3; i++)
      msg->follow_target.position_cov[i] = read_float32(p);
    msg->follow_target.est_capabilities = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CONTROL_SYSTEM_STATE:
    msg->control_system_state.time_usec = read_uint64(p);
    msg->control_system_state.x_acc = read_float32(p);
    msg->control_system_state.y_acc = read_float32(p);
    msg->control_system_state.z_acc = read_float32(p);
    msg->control_system_state.x_vel = read_float32(p);
    msg->control_system_state.y_vel = read_float32(p);
    msg->control_system_state.z_vel = read_float32(p);
    msg->control_system_state.x_pos = read_float32(p);
    msg->control_system_state.y_pos = read_float32(p);
    msg->control_system_state.z_pos = read_float32(p);
    msg->control_system_state.airspeed = read_float32(p);
    for (size_t i = 0; i < 3; i++)
      msg->control_system_state.vel_variance[i] = read_float32(p);
    for (size_t i = 0; i < 3; i++)
      msg->control_system_state.pos_variance[i] = read_float32(p);
    for (size_t i = 0; i < 4; i++)
      msg->control_system_state.q[i] = read_float32(p);
    msg->control_system_state.roll_rate = read_float32(p);
    msg->control_system_state.pitch_rate = read_float32(p);
    msg->control_system_state.yaw_rate = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_BATTERY_STATUS:
    msg->battery_status.current_consumed = read_int32(p);
    msg->battery_status.energy_consumed = read_int32(p);
    msg->battery_status.temperature = read_int16(p);
    for (size_t i = 0; i < 10; i++)
      msg->battery_status.voltages[i] = read_uint16(p);
    msg->battery_status.current_battery = read_int16(p);
    msg->battery_status.id = read_byte(p);
    msg->battery_status.battery_function = read_byte(p);
    msg->battery_status.type = read_byte(p);
    msg->battery_status.battery_remaining = read_int8(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_AUTOPILOT_VERSION:
    msg->autopilot_version.capabilities = read_uint64(p);
    msg->autopilot_version.uid = read_uint64(p);
    msg->autopilot_version.flight_sw_version = read_uint32(p);
    msg->autopilot_version.middleware_sw_version = read_uint32(p);
    msg->autopilot_version.os_sw_version = read_uint32(p);
    msg->autopilot_version.board_version = read_uint32(p);
    msg->autopilot_version.vendor_id = read_uint16(p);
    msg->autopilot_version.product_id = read_uint16(p);
    for (size_t i = 0; i < 8; i++)
      msg->autopilot_version.flight_custom_version[i] = read_byte(p);
    for (size_t i = 0; i < 8; i++)
      msg->autopilot_version.middleware_custom_version[i] = read_byte(p);
    for (size_t i = 0; i < 8; i++)
      msg->autopilot_version.os_custom_version[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LANDING_TARGET:
    msg->landing_target.time_usec = read_uint64(p);
    msg->landing_target.angle_x = read_float32(p);
    msg->landing_target.angle_y = read_float32(p);
    msg->landing_target.distance = read_float32(p);
    msg->landing_target.size_x = read_float32(p);
    msg->landing_target.size_y = read_float32(p);
    msg->landing_target.target_num = read_byte(p);
    msg->landing_target.frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_0:

    for (size_t i = 0; i < 4; i++)
      msg->array_test_0.ar_u32[i] = read_uint32(p);
    for (size_t i = 0; i < 4; i++)
      msg->array_test_0.ar_u16[i] = read_uint16(p);
    msg->array_test_0.v1 = read_byte(p);
    for (size_t i = 0; i < 4; i++)
      msg->array_test_0.ar_i8[i] = read_int8(p);
    for (size_t i = 0; i < 4; i++)
      msg->array_test_0.ar_u8[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_1:

    for (size_t i = 0; i < 4; i++)
      msg->array_test_1.ar_u32[i] = read_uint32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_3:

    for (size_t i = 0; i < 4; i++)
      msg->array_test_3.ar_u32[i] = read_uint32(p);
    msg->array_test_3.v = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_4:

    for (size_t i = 0; i < 4; i++)
      msg->array_test_4.ar_u32[i] = read_uint32(p);
    msg->array_test_4.v = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_5:

    for (size_t i = 0; i < 5; i++)
      msg->array_test_5.c1[i] = read_byte(p);
    for (size_t i = 0; i < 5; i++)
      msg->array_test_5.c2[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_6:

    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_d[i] = read_float64(p);
    msg->array_test_6.v3 = read_uint32(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_u32[i] = read_uint32(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_i32[i] = read_int32(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_f[i] = read_float32(p);
    msg->array_test_6.v2 = read_uint16(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_u16[i] = read_uint16(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_i16[i] = read_int16(p);
    msg->array_test_6.v1 = read_byte(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_u8[i] = read_byte(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_6.ar_i8[i] = read_int8(p);
    for (size_t i = 0; i < 32; i++)
      msg->array_test_6.ar_c[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_7:

    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_d[i] = read_float64(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_f[i] = read_float32(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_u32[i] = read_uint32(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_i32[i] = read_int32(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_u16[i] = read_uint16(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_i16[i] = read_int16(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_u8[i] = read_byte(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_7.ar_i8[i] = read_int8(p);
    for (size_t i = 0; i < 32; i++)
      msg->array_test_7.ar_c[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ARRAY_TEST_8:

    for (size_t i = 0; i < 2; i++)
      msg->array_test_8.ar_d[i] = read_float64(p);
    msg->array_test_8.v3 = read_uint32(p);
    for (size_t i = 0; i < 2; i++)
      msg->array_test_8.ar_u16[i] = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ESTIMATOR_STATUS:
    msg->estimator_status.time_usec = read_uint64(p);
    msg->estimator_status.vel_ratio = read_float32(p);
    msg->estimator_status.pos_horiz_ratio = read_float32(p);
    msg->estimator_status.pos_vert_ratio = read_float32(p);
    msg->estimator_status.mag_ratio = read_float32(p);
    msg->estimator_status.hagl_ratio = read_float32(p);
    msg->estimator_status.tas_ratio = read_float32(p);
    msg->estimator_status.pos_horiz_accuracy = read_float32(p);
    msg->estimator_status.pos_vert_accuracy = read_float32(p);
    msg->estimator_status.flags = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_WIND_COV:
    msg->wind_cov.time_usec = read_uint64(p);
    msg->wind_cov.wind_x = read_float32(p);
    msg->wind_cov.wind_y = read_float32(p);
    msg->wind_cov.wind_z = read_float32(p);
    msg->wind_cov.var_horiz = read_float32(p);
    msg->wind_cov.var_vert = read_float32(p);
    msg->wind_cov.wind_alt = read_float32(p);
    msg->wind_cov.horiz_accuracy = read_float32(p);
    msg->wind_cov.vert_accuracy = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_INPUT:
    msg->gps_input.time_usec = read_uint64(p);
    msg->gps_input.time_week_ms = read_uint32(p);
    msg->gps_input.lat = read_int32(p);
    msg->gps_input.lon = read_int32(p);
    msg->gps_input.alt = read_float32(p);
    msg->gps_input.hdop = read_float32(p);
    msg->gps_input.vdop = read_float32(p);
    msg->gps_input.vn = read_float32(p);
    msg->gps_input.ve = read_float32(p);
    msg->gps_input.vd = read_float32(p);
    msg->gps_input.speed_accuracy = read_float32(p);
    msg->gps_input.horiz_accuracy = read_float32(p);
    msg->gps_input.vert_accuracy = read_float32(p);
    msg->gps_input.ignore_flags = read_uint16(p);
    msg->gps_input.time_week = read_uint16(p);
    msg->gps_input.gps_id = read_byte(p);
    msg->gps_input.fix_type = read_byte(p);
    msg->gps_input.satellites_visible = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_RTCM_DATA:
    msg->gps_rtcm_data.flags = read_byte(p);
    msg->gps_rtcm_data.len = read_byte(p);
    for (size_t i = 0; i < 180; i++)
      msg->gps_rtcm_data.data[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIGH_LATENCY:
    msg->high_latency.custom_mode = read_uint32(p);
    msg->high_latency.latitude = read_int32(p);
    msg->high_latency.longitude = read_int32(p);
    msg->high_latency.roll = read_int16(p);
    msg->high_latency.pitch = read_int16(p);
    msg->high_latency.heading = read_uint16(p);
    msg->high_latency.heading_sp = read_int16(p);
    msg->high_latency.altitude_amsl = read_int16(p);
    msg->high_latency.altitude_sp = read_int16(p);
    msg->high_latency.wp_distance = read_uint16(p);
    msg->high_latency.base_mode = read_byte(p);
    msg->high_latency.landed_state = read_byte(p);
    msg->high_latency.throttle = read_int8(p);
    msg->high_latency.airspeed = read_byte(p);
    msg->high_latency.airspeed_sp = read_byte(p);
    msg->high_latency.groundspeed = read_byte(p);
    msg->high_latency.climb_rate = read_int8(p);
    msg->high_latency.gps_nsat = read_byte(p);
    msg->high_latency.gps_fix_type = read_byte(p);
    msg->high_latency.battery_remaining = read_byte(p);
    msg->high_latency.temperature = read_int8(p);
    msg->high_latency.temperature_air = read_int8(p);
    msg->high_latency.failsafe = read_byte(p);
    msg->high_latency.wp_num = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HIGH_LATENCY2:
    msg->high_latency2.timestamp = read_uint32(p);
    msg->high_latency2.latitude = read_int32(p);
    msg->high_latency2.longitude = read_int32(p);
    msg->high_latency2.custom_mode = read_uint16(p);
    msg->high_latency2.altitude = read_int16(p);
    msg->high_latency2.target_altitude = read_int16(p);
    msg->high_latency2.target_distance = read_uint16(p);
    msg->high_latency2.wp_num = read_uint16(p);
    msg->high_latency2.failure_flags = read_uint16(p);
    msg->high_latency2.type = read_byte(p);
    msg->high_latency2.autopilot = read_byte(p);
    msg->high_latency2.heading = read_byte(p);
    msg->high_latency2.target_heading = read_byte(p);
    msg->high_latency2.throttle = read_byte(p);
    msg->high_latency2.airspeed = read_byte(p);
    msg->high_latency2.airspeed_sp = read_byte(p);
    msg->high_latency2.groundspeed = read_byte(p);
    msg->high_latency2.windspeed = read_byte(p);
    msg->high_latency2.wind_heading = read_byte(p);
    msg->high_latency2.eph = read_byte(p);
    msg->high_latency2.epv = read_byte(p);
    msg->high_latency2.temperature_air = read_int8(p);
    msg->high_latency2.climb_rate = read_int8(p);
    msg->high_latency2.battery = read_int8(p);
    msg->high_latency2.custom0 = read_int8(p);
    msg->high_latency2.custom1 = read_int8(p);
    msg->high_latency2.custom2 = read_int8(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VIBRATION:
    msg->vibration.time_usec = read_uint64(p);
    msg->vibration.vibration_x = read_float32(p);
    msg->vibration.vibration_y = read_float32(p);
    msg->vibration.vibration_z = read_float32(p);
    msg->vibration.clipping_0 = read_uint32(p);
    msg->vibration.clipping_1 = read_uint32(p);
    msg->vibration.clipping_2 = read_uint32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HOME_POSITION:
    msg->home_position.latitude = read_int32(p);
    msg->home_position.longitude = read_int32(p);
    msg->home_position.altitude = read_int32(p);
    msg->home_position.x = read_float32(p);
    msg->home_position.y = read_float32(p);
    msg->home_position.z = read_float32(p);
    for (size_t i = 0; i < 4; i++)
      msg->home_position.q[i] = read_float32(p);
    msg->home_position.approach_x = read_float32(p);
    msg->home_position.approach_y = read_float32(p);
    msg->home_position.approach_z = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_HOME_POSITION:
    msg->set_home_position.latitude = read_int32(p);
    msg->set_home_position.longitude = read_int32(p);
    msg->set_home_position.altitude = read_int32(p);
    msg->set_home_position.x = read_float32(p);
    msg->set_home_position.y = read_float32(p);
    msg->set_home_position.z = read_float32(p);
    for (size_t i = 0; i < 4; i++)
      msg->set_home_position.q[i] = read_float32(p);
    msg->set_home_position.approach_x = read_float32(p);
    msg->set_home_position.approach_y = read_float32(p);
    msg->set_home_position.approach_z = read_float32(p);
    msg->set_home_position.target_system = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MESSAGE_INTERVAL:
    msg->message_interval.interval_us = read_int32(p);
    msg->message_interval.message_id = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_EXTENDED_SYS_STATE:
    msg->extended_sys_state.vtol_state = read_byte(p);
    msg->extended_sys_state.landed_state = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ADSB_VEHICLE:
    msg->adsb_vehicle.ICAO_address = read_uint32(p);
    msg->adsb_vehicle.lat = read_int32(p);
    msg->adsb_vehicle.lon = read_int32(p);
    msg->adsb_vehicle.altitude = read_int32(p);
    msg->adsb_vehicle.heading = read_uint16(p);
    msg->adsb_vehicle.hor_velocity = read_uint16(p);
    msg->adsb_vehicle.ver_velocity = read_int16(p);
    msg->adsb_vehicle.flags = read_uint16(p);
    msg->adsb_vehicle.squawk = read_uint16(p);
    msg->adsb_vehicle.altitude_type = read_byte(p);
    for (size_t i = 0; i < 9; i++)
      msg->adsb_vehicle.callsign[i] = read_byte(p);
    msg->adsb_vehicle.emitter_type = read_byte(p);
    msg->adsb_vehicle.tslc = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_COLLISION:
    msg->collision.id = read_uint32(p);
    msg->collision.time_to_minimum_delta = read_float32(p);
    msg->collision.altitude_minimum_delta = read_float32(p);
    msg->collision.horizontal_minimum_delta = read_float32(p);
    msg->collision.src = read_byte(p);
    msg->collision.action = read_byte(p);
    msg->collision.threat_level = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_V2_EXTENSION:
    msg->v2_extension.message_type = read_uint16(p);
    msg->v2_extension.target_network = read_byte(p);
    msg->v2_extension.target_system = read_byte(p);
    msg->v2_extension.target_component = read_byte(p);
    for (size_t i = 0; i < 249; i++)
      msg->v2_extension.payload[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MEMORY_VECT:
    msg->memory_vect.address = read_uint16(p);
    msg->memory_vect.ver = read_byte(p);
    msg->memory_vect.type = read_byte(p);
    for (size_t i = 0; i < 32; i++)
      msg->memory_vect.value[i] = read_int8(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DEBUG_VECT:
    msg->debug_vect.time_usec = read_uint64(p);
    msg->debug_vect.x = read_float32(p);
    msg->debug_vect.y = read_float32(p);
    msg->debug_vect.z = read_float32(p);
    for (size_t i = 0; i < 10; i++)
      msg->debug_vect.name[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_NAMED_VALUE_FLOAT:
    msg->named_value_float.time_boot_ms = read_uint32(p);
    msg->named_value_float.value = read_float32(p);
    for (size_t i = 0; i < 10; i++)
      msg->named_value_float.name[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_NAMED_VALUE_INT:
    msg->named_value_int.time_boot_ms = read_uint32(p);
    msg->named_value_int.value = read_int32(p);
    for (size_t i = 0; i < 10; i++)
      msg->named_value_int.name[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_STATUSTEXT:
    msg->statustext.severity = read_byte(p);
    for (size_t i = 0; i < 50; i++)
      msg->statustext.text[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DEBUG:
    msg->debug.time_boot_ms = read_uint32(p);
    msg->debug.value = read_float32(p);
    msg->debug.ind = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SETUP_SIGNING:
    msg->setup_signing.initial_timestamp = read_uint64(p);
    msg->setup_signing.target_system = read_byte(p);
    msg->setup_signing.target_component = read_byte(p);
    for (size_t i = 0; i < 32; i++)
      msg->setup_signing.secret_key[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_BUTTON_CHANGE:
    msg->button_change.time_boot_ms = read_uint32(p);
    msg->button_change.last_change_ms = read_uint32(p);
    msg->button_change.state = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PLAY_TUNE:
    msg->play_tune.target_system = read_byte(p);
    msg->play_tune.target_component = read_byte(p);
    for (size_t i = 0; i < 30; i++)
      msg->play_tune.tune[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CAMERA_INFORMATION:
    msg->camera_information.time_boot_ms = read_uint32(p);
    msg->camera_information.firmware_version = read_uint32(p);
    msg->camera_information.focal_length = read_float32(p);
    msg->camera_information.sensor_size_h = read_float32(p);
    msg->camera_information.sensor_size_v = read_float32(p);
    msg->camera_information.flags = read_uint32(p);
    msg->camera_information.resolution_h = read_uint16(p);
    msg->camera_information.resolution_v = read_uint16(p);
    msg->camera_information.cam_definition_version = read_uint16(p);
    for (size_t i = 0; i < 32; i++)
      msg->camera_information.vendor_name[i] = read_byte(p);
    for (size_t i = 0; i < 32; i++)
      msg->camera_information.model_name[i] = read_byte(p);
    msg->camera_information.lens_id = read_byte(p);
    for (size_t i = 0; i < 140; i++)
      msg->camera_information.cam_definition_uri[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CAMERA_SETTINGS:
    msg->camera_settings.time_boot_ms = read_uint32(p);
    msg->camera_settings.mode_id = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_STORAGE_INFORMATION:
    msg->storage_information.time_boot_ms = read_uint32(p);
    msg->storage_information.total_capacity = read_float32(p);
    msg->storage_information.used_capacity = read_float32(p);
    msg->storage_information.available_capacity = read_float32(p);
    msg->storage_information.read_speed = read_float32(p);
    msg->storage_information.write_speed = read_float32(p);
    msg->storage_information.storage_id = read_byte(p);
    msg->storage_information.storage_count = read_byte(p);
    msg->storage_information.status = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CAMERA_CAPTURE_STATUS:
    msg->camera_capture_status.time_boot_ms = read_uint32(p);
    msg->camera_capture_status.image_interval = read_float32(p);
    msg->camera_capture_status.recording_time_ms = read_uint32(p);
    msg->camera_capture_status.available_capacity = read_float32(p);
    msg->camera_capture_status.image_status = read_byte(p);
    msg->camera_capture_status.video_status = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CAMERA_IMAGE_CAPTURED:
    msg->camera_image_captured.time_utc = read_uint64(p);
    msg->camera_image_captured.time_boot_ms = read_uint32(p);
    msg->camera_image_captured.lat = read_int32(p);
    msg->camera_image_captured.lon = read_int32(p);
    msg->camera_image_captured.alt = read_int32(p);
    msg->camera_image_captured.relative_alt = read_int32(p);
    for (size_t i = 0; i < 4; i++)
      msg->camera_image_captured.q[i] = read_float32(p);
    msg->camera_image_captured.image_index = read_int32(p);
    msg->camera_image_captured.camera_id = read_byte(p);
    msg->camera_image_captured.capture_result = read_int8(p);
    for (size_t i = 0; i < 205; i++)
      msg->camera_image_captured.file_url[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_FLIGHT_INFORMATION:
    msg->flight_information.arming_time_utc = read_uint64(p);
    msg->flight_information.takeoff_time_utc = read_uint64(p);
    msg->flight_information.flight_uuid = read_uint64(p);
    msg->flight_information.time_boot_ms = read_uint32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MOUNT_ORIENTATION:
    msg->mount_orientation.time_boot_ms = read_uint32(p);
    msg->mount_orientation.roll = read_float32(p);
    msg->mount_orientation.pitch = read_float32(p);
    msg->mount_orientation.yaw = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOGGING_DATA:
    msg->logging_data.sequence = read_uint16(p);
    msg->logging_data.target_system = read_byte(p);
    msg->logging_data.target_component = read_byte(p);
    msg->logging_data.length = read_byte(p);
    msg->logging_data.first_message_offset = read_byte(p);
    for (size_t i = 0; i < 249; i++)
      msg->logging_data.data[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOGGING_DATA_ACKED:
    msg->logging_data_acked.sequence = read_uint16(p);
    msg->logging_data_acked.target_system = read_byte(p);
    msg->logging_data_acked.target_component = read_byte(p);
    msg->logging_data_acked.length = read_byte(p);
    msg->logging_data_acked.first_message_offset = read_byte(p);
    for (size_t i = 0; i < 249; i++)
      msg->logging_data_acked.data[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LOGGING_ACK:
    msg->logging_ack.sequence = read_uint16(p);
    msg->logging_ack.target_system = read_byte(p);
    msg->logging_ack.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VIDEO_STREAM_INFORMATION:
    msg->video_stream_information.framerate = read_float32(p);
    msg->video_stream_information.bitrate = read_uint32(p);
    msg->video_stream_information.flags = read_uint16(p);
    msg->video_stream_information.resolution_h = read_uint16(p);
    msg->video_stream_information.resolution_v = read_uint16(p);
    msg->video_stream_information.rotation = read_uint16(p);
    msg->video_stream_information.hfov = read_uint16(p);
    msg->video_stream_information.stream_id = read_byte(p);
    msg->video_stream_information.count = read_byte(p);
    msg->video_stream_information.type = read_byte(p);
    for (size_t i = 0; i < 32; i++)
      msg->video_stream_information.name[i] = read_byte(p);
    for (size_t i = 0; i < 160; i++)
      msg->video_stream_information.uri[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VIDEO_STREAM_STATUS:
    msg->video_stream_status.framerate = read_float32(p);
    msg->video_stream_status.bitrate = read_uint32(p);
    msg->video_stream_status.flags = read_uint16(p);
    msg->video_stream_status.resolution_h = read_uint16(p);
    msg->video_stream_status.resolution_v = read_uint16(p);
    msg->video_stream_status.rotation = read_uint16(p);
    msg->video_stream_status.hfov = read_uint16(p);
    msg->video_stream_status.stream_id = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_WIFI_CONFIG_AP:

    for (size_t i = 0; i < 32; i++)
      msg->wifi_config_ap.ssid[i] = read_byte(p);
    for (size_t i = 0; i < 64; i++)
      msg->wifi_config_ap.password[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PROTOCOL_VERSION:
    msg->protocol_version.version = read_uint16(p);
    msg->protocol_version.min_version = read_uint16(p);
    msg->protocol_version.max_version = read_uint16(p);
    for (size_t i = 0; i < 8; i++)
      msg->protocol_version.spec_version_hash[i] = read_byte(p);
    for (size_t i = 0; i < 8; i++)
      msg->protocol_version.library_version_hash[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_UAVCAN_NODE_STATUS:
    msg->uavcan_node_status.time_usec = read_uint64(p);
    msg->uavcan_node_status.uptime_sec = read_uint32(p);
    msg->uavcan_node_status.vendor_specific_status_code = read_uint16(p);
    msg->uavcan_node_status.health = read_byte(p);
    msg->uavcan_node_status.mode = read_byte(p);
    msg->uavcan_node_status.sub_mode = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_UAVCAN_NODE_INFO:
    msg->uavcan_node_info.time_usec = read_uint64(p);
    msg->uavcan_node_info.uptime_sec = read_uint32(p);
    msg->uavcan_node_info.sw_vcs_commit = read_uint32(p);
    for (size_t i = 0; i < 80; i++)
      msg->uavcan_node_info.name[i] = read_byte(p);
    msg->uavcan_node_info.hw_version_major = read_byte(p);
    msg->uavcan_node_info.hw_version_minor = read_byte(p);
    for (size_t i = 0; i < 16; i++)
      msg->uavcan_node_info.hw_unique_id[i] = read_byte(p);
    msg->uavcan_node_info.sw_version_major = read_byte(p);
    msg->uavcan_node_info.sw_version_minor = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_EXT_REQUEST_READ:
    msg->param_ext_request_read.param_index = read_int16(p);
    msg->param_ext_request_read.target_system = read_byte(p);
    msg->param_ext_request_read.target_component = read_byte(p);
    for (size_t i = 0; i < 16; i++)
      msg->param_ext_request_read.param_id[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_EXT_REQUEST_LIST:
    msg->param_ext_request_list.target_system = read_byte(p);
    msg->param_ext_request_list.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_EXT_VALUE:
    msg->param_ext_value.param_count = read_uint16(p);
    msg->param_ext_value.param_index = read_uint16(p);
    for (size_t i = 0; i < 16; i++)
      msg->param_ext_value.param_id[i] = read_byte(p);
    for (size_t i = 0; i < 128; i++)
      msg->param_ext_value.param_value[i] = read_byte(p);
    msg->param_ext_value.param_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_EXT_SET:
    msg->param_ext_set.target_system = read_byte(p);
    msg->param_ext_set.target_component = read_byte(p);
    for (size_t i = 0; i < 16; i++)
      msg->param_ext_set.param_id[i] = read_byte(p);
    for (size_t i = 0; i < 128; i++)
      msg->param_ext_set.param_value[i] = read_byte(p);
    msg->param_ext_set.param_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PARAM_EXT_ACK:

    for (size_t i = 0; i < 16; i++)
      msg->param_ext_ack.param_id[i] = read_byte(p);
    for (size_t i = 0; i < 128; i++)
      msg->param_ext_ack.param_value[i] = read_byte(p);
    msg->param_ext_ack.param_type = read_byte(p);
    msg->param_ext_ack.param_result = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_OBSTACLE_DISTANCE:
    msg->obstacle_distance.time_usec = read_uint64(p);
    for (size_t i = 0; i < 72; i++)
      msg->obstacle_distance.distances[i] = read_uint16(p);
    msg->obstacle_distance.min_distance = read_uint16(p);
    msg->obstacle_distance.max_distance = read_uint16(p);
    msg->obstacle_distance.sensor_type = read_byte(p);
    msg->obstacle_distance.increment = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ODOMETRY:
    msg->odometry.time_usec = read_uint64(p);
    msg->odometry.x = read_float32(p);
    msg->odometry.y = read_float32(p);
    msg->odometry.z = read_float32(p);
    for (size_t i = 0; i < 4; i++)
      msg->odometry.q[i] = read_float32(p);
    msg->odometry.vx = read_float32(p);
    msg->odometry.vy = read_float32(p);
    msg->odometry.vz = read_float32(p);
    msg->odometry.rollspeed = read_float32(p);
    msg->odometry.pitchspeed = read_float32(p);
    msg->odometry.yawspeed = read_float32(p);
    for (size_t i = 0; i < 21; i++)
      msg->odometry.pose_covariance[i] = read_float32(p);
    for (size_t i = 0; i < 21; i++)
      msg->odometry.velocity_covariance[i] = read_float32(p);
    msg->odometry.frame_id = read_byte(p);
    msg->odometry.child_frame_id = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TRAJECTORY_REPRESENTATION_WAYPOINTS:
    msg->trajectory_representation_waypoints.time_usec = read_uint64(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.pos_x[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.pos_y[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.pos_z[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.vel_x[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.vel_y[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.vel_z[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.acc_x[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.acc_y[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.acc_z[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.pos_yaw[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_waypoints.vel_yaw[i] = read_float32(p);
    msg->trajectory_representation_waypoints.valid_points = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TRAJECTORY_REPRESENTATION_BEZIER:
    msg->trajectory_representation_bezier.time_usec = read_uint64(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_bezier.pos_x[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_bezier.pos_y[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_bezier.pos_z[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_bezier.delta[i] = read_float32(p);
    for (size_t i = 0; i < 5; i++)
      msg->trajectory_representation_bezier.pos_yaw[i] = read_float32(p);
    msg->trajectory_representation_bezier.valid_points = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CELLULAR_STATUS:
    msg->cellular_status.cid = read_uint32(p);
    msg->cellular_status.status = read_uint16(p);
    msg->cellular_status.mcc = read_uint16(p);
    msg->cellular_status.mnc = read_uint16(p);
    msg->cellular_status.lac = read_uint16(p);
    msg->cellular_status.type = read_byte(p);
    msg->cellular_status.quality = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ISBD_LINK_STATUS:
    msg->isbd_link_status.timestamp = read_uint64(p);
    msg->isbd_link_status.last_heartbeat = read_uint64(p);
    msg->isbd_link_status.failed_sessions = read_uint16(p);
    msg->isbd_link_status.successful_sessions = read_uint16(p);
    msg->isbd_link_status.signal_quality = read_byte(p);
    msg->isbd_link_status.ring_pending = read_byte(p);
    msg->isbd_link_status.tx_session_pending = read_byte(p);
    msg->isbd_link_status.rx_session_pending = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_UTM_GLOBAL_POSITION:
    msg->utm_global_position.time = read_uint64(p);
    msg->utm_global_position.lat = read_int32(p);
    msg->utm_global_position.lon = read_int32(p);
    msg->utm_global_position.alt = read_int32(p);
    msg->utm_global_position.relative_alt = read_int32(p);
    msg->utm_global_position.next_lat = read_int32(p);
    msg->utm_global_position.next_lon = read_int32(p);
    msg->utm_global_position.next_alt = read_int32(p);
    msg->utm_global_position.vx = read_int16(p);
    msg->utm_global_position.vy = read_int16(p);
    msg->utm_global_position.vz = read_int16(p);
    msg->utm_global_position.h_acc = read_uint16(p);
    msg->utm_global_position.v_acc = read_uint16(p);
    msg->utm_global_position.vel_acc = read_uint16(p);
    msg->utm_global_position.update_rate = read_uint16(p);
    for (size_t i = 0; i < 18; i++)
      msg->utm_global_position.uas_id[i] = read_byte(p);
    msg->utm_global_position.flight_state = read_byte(p);
    msg->utm_global_position.flags = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DEBUG_FLOAT_ARRAY:
    msg->debug_float_array.time_usec = read_uint64(p);
    msg->debug_float_array.array_id = read_uint16(p);
    for (size_t i = 0; i < 10; i++)
      msg->debug_float_array.name[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ORBIT_EXECUTION_STATUS:
    msg->orbit_execution_status.time_usec = read_uint64(p);
    msg->orbit_execution_status.radius = read_float32(p);
    msg->orbit_execution_status.x = read_int32(p);
    msg->orbit_execution_status.y = read_int32(p);
    msg->orbit_execution_status.z = read_float32(p);
    msg->orbit_execution_status.frame = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_STATUSTEXT_LONG:
    msg->statustext_long.severity = read_byte(p);
    for (size_t i = 0; i < 254; i++)
      msg->statustext_long.text[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SMART_BATTERY_INFO:
    msg->smart_battery_info.capacity_full_specification = read_int32(p);
    msg->smart_battery_info.capacity_full = read_int32(p);
    msg->smart_battery_info.serial_number = read_int32(p);
    msg->smart_battery_info.cycle_count = read_uint16(p);
    msg->smart_battery_info.weight = read_uint16(p);
    msg->smart_battery_info.discharge_minimum_voltage = read_uint16(p);
    msg->smart_battery_info.charging_minimum_voltage = read_uint16(p);
    msg->smart_battery_info.resting_minimum_voltage = read_uint16(p);
    msg->smart_battery_info.id = read_byte(p);
    for (size_t i = 0; i < 50; i++)
      msg->smart_battery_info.device_name[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SMART_BATTERY_STATUS:
    msg->smart_battery_status.fault_bitmask = read_int32(p);
    msg->smart_battery_status.time_remaining = read_int32(p);
    msg->smart_battery_status.id = read_uint16(p);
    msg->smart_battery_status.capacity_remaining = read_int16(p);
    msg->smart_battery_status.current = read_int16(p);
    msg->smart_battery_status.temperature = read_int16(p);
    msg->smart_battery_status.cell_offset = read_uint16(p);
    for (size_t i = 0; i < 16; i++)
      msg->smart_battery_status.voltages[i] = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ACTUATOR_OUTPUT_STATUS:
    msg->actuator_output_status.time_usec = read_uint64(p);
    msg->actuator_output_status.active = read_uint32(p);
    for (size_t i = 0; i < 32; i++)
      msg->actuator_output_status.actuator[i] = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_TIME_ESTIMATE_TO_TARGET:
    msg->time_estimate_to_target.safe_return = read_int32(p);
    msg->time_estimate_to_target.land = read_int32(p);
    msg->time_estimate_to_target.mission_next_item = read_int32(p);
    msg->time_estimate_to_target.mission_end = read_int32(p);
    msg->time_estimate_to_target.commanded_action = read_int32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_WHEEL_DISTANCE:
    msg->wheel_distance.time_usec = read_uint64(p);
    for (size_t i = 0; i < 16; i++)
      msg->wheel_distance.distance[i] = read_float64(p);
    msg->wheel_distance.count = read_byte(p);
    break;
  };
}

static void read_payload_ext(const uint8_t **p,
                             struct python_array_test_message *msg) {
  switch (msg->msg_id) {

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_RAW_INT:
    msg->gps_raw_int.alt_ellipsoid = read_int32(p);
    msg->gps_raw_int.h_acc = read_uint32(p);
    msg->gps_raw_int.v_acc = read_uint32(p);
    msg->gps_raw_int.vel_acc = read_uint32(p);
    msg->gps_raw_int.hdg_acc = read_uint32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SERVO_OUTPUT_RAW:
    msg->servo_output_raw.servo9_raw = read_uint16(p);
    msg->servo_output_raw.servo10_raw = read_uint16(p);
    msg->servo_output_raw.servo11_raw = read_uint16(p);
    msg->servo_output_raw.servo12_raw = read_uint16(p);
    msg->servo_output_raw.servo13_raw = read_uint16(p);
    msg->servo_output_raw.servo14_raw = read_uint16(p);
    msg->servo_output_raw.servo15_raw = read_uint16(p);
    msg->servo_output_raw.servo16_raw = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST_PARTIAL_LIST:
    msg->mission_request_partial_list.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_WRITE_PARTIAL_LIST:
    msg->mission_write_partial_list.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_ITEM:
    msg->mission_item.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST:
    msg->mission_request.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST_LIST:
    msg->mission_request_list.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_COUNT:
    msg->mission_count.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_CLEAR_ALL:
    msg->mission_clear_all.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_ACK:
    msg->mission_ack.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_GPS_GLOBAL_ORIGIN:
    msg->set_gps_global_origin.time_usec = read_uint64(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GPS_GLOBAL_ORIGIN:
    msg->gps_global_origin.time_usec = read_uint64(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_REQUEST_INT:
    msg->mission_request_int.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_RC_CHANNELS_OVERRIDE:
    msg->rc_channels_override.chan9_raw = read_uint16(p);
    msg->rc_channels_override.chan10_raw = read_uint16(p);
    msg->rc_channels_override.chan11_raw = read_uint16(p);
    msg->rc_channels_override.chan12_raw = read_uint16(p);
    msg->rc_channels_override.chan13_raw = read_uint16(p);
    msg->rc_channels_override.chan14_raw = read_uint16(p);
    msg->rc_channels_override.chan15_raw = read_uint16(p);
    msg->rc_channels_override.chan16_raw = read_uint16(p);
    msg->rc_channels_override.chan17_raw = read_uint16(p);
    msg->rc_channels_override.chan18_raw = read_uint16(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MISSION_ITEM_INT:
    msg->mission_item_int.mission_type = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_COMMAND_ACK:
    msg->command_ack.result_param2 = read_int32(p);
    msg->command_ack.progress = read_byte(p);
    msg->command_ack.target_system = read_byte(p);
    msg->command_ack.target_component = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_OPTICAL_FLOW:
    msg->optical_flow.flow_rate_x = read_float32(p);
    msg->optical_flow.flow_rate_y = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_GLOBAL_VISION_POSITION_ESTIMATE:
    for (size_t i = 0; i < 21; i++)
      msg->global_vision_position_estimate.covariance[i] = read_float32(p);
    msg->global_vision_position_estimate.reset_counter = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VISION_POSITION_ESTIMATE:
    for (size_t i = 0; i < 21; i++)
      msg->vision_position_estimate.covariance[i] = read_float32(p);
    msg->vision_position_estimate.reset_counter = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VISION_SPEED_ESTIMATE:
    for (size_t i = 0; i < 9; i++)
      msg->vision_speed_estimate.covariance[i] = read_float32(p);
    msg->vision_speed_estimate.reset_counter = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_VICON_POSITION_ESTIMATE:
    for (size_t i = 0; i < 21; i++)
      msg->vicon_position_estimate.covariance[i] = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DISTANCE_SENSOR:
    msg->distance_sensor.horizontal_fov = read_float32(p);
    msg->distance_sensor.vertical_fov = read_float32(p);
    for (size_t i = 0; i < 4; i++)
      msg->distance_sensor.quaternion[i] = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ATT_POS_MOCAP:
    for (size_t i = 0; i < 21; i++)
      msg->att_pos_mocap.covariance[i] = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_BATTERY_STATUS:
    msg->battery_status.time_remaining = read_int32(p);
    msg->battery_status.charge_state = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_AUTOPILOT_VERSION:
    for (size_t i = 0; i < 18; i++)
      msg->autopilot_version.uid2[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_LANDING_TARGET:
    msg->landing_target.x = read_float32(p);
    msg->landing_target.y = read_float32(p);
    msg->landing_target.z = read_float32(p);
    for (size_t i = 0; i < 4; i++)
      msg->landing_target.q[i] = read_float32(p);
    msg->landing_target.type = read_byte(p);
    msg->landing_target.position_valid = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_HOME_POSITION:
    msg->home_position.time_usec = read_uint64(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_SET_HOME_POSITION:
    msg->set_home_position.time_usec = read_uint64(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_PLAY_TUNE:
    for (size_t i = 0; i < 200; i++)
      msg->play_tune.tune2[i] = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_CAMERA_SETTINGS:
    msg->camera_settings.zoomLevel = read_float32(p);
    msg->camera_settings.focusLevel = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_MOUNT_ORIENTATION:
    msg->mount_orientation.yaw_absolute = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_OBSTACLE_DISTANCE:
    msg->obstacle_distance.increment_f = read_float32(p);
    msg->obstacle_distance.angle_offset = read_float32(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_ODOMETRY:
    msg->odometry.reset_counter = read_byte(p);
    break;

  case PYTHON_ARRAY_TEST_MESSAGE_DEBUG_FLOAT_ARRAY:
    for (size_t i = 0; i < 58; i++)
      msg->debug_float_array.data[i] = read_float32(p);
    break;

  default:; // nix
  };
}

size_t
python_array_test_message_deserialize(const uint8_t *buf, size_t size,
                                      struct python_array_test_message *msg) {
  if (size < 3) {
    return 0;
  }
  switch (buf[0]) {
  case 0xFE:
    if (size < 9 + buf[1]) {
      return 0;
    }
    break;
  case 0xFD:
    if (size < 12 + buf[1] + ((buf[2] & 0x1) ? 13 : 0)) {
      return 0;
    }
    break;
  default:
    return 0;
  }

  const uint8_t *p = buf + 1;

  msg->len = *p++;

  if (buf[0] == 0xFD) {
    p += 2; // skip incompat + compat flags
  }

  msg->seq_dropped =
      *p++ - 1 -
      (uint8_t)(msg->seq_nr); // add difference in least significant byte
  msg->seq_nr += 1 + msg->seq_dropped;

  msg->sys_id = *p++;
  msg->comp_id = *p++;
  msg->msg_id = *p++;
  if (buf[0] == 0xFD) {
    msg->msg_id |= (uint32_t)(*p++) << 8;
    msg->msg_id |= (uint32_t)(*p++) << 16;
  }

  uint8_t tmp[256];
  memset(tmp, 0, sizeof tmp);
  memmove(tmp, p, msg->len);
  p += msg->len;

  uint16_t crc = 0xffff;
  for (const uint8_t *pp = buf + 1; pp < p; ++pp) {
    crc = x25(crc, *pp);
  }
  crc = x25(crc, python_array_test_crcextra(msg->msg_id));

  crc ^= *p++;
  crc ^= *p++ << 8;
  msg->crc = crc; // should be zero now

  const uint8_t *q = tmp;
  read_payload_base(&q, msg);
  if (buf[0] == 0xFD) {
    read_payload_ext(&q, msg);
  }
  assert(q - tmp < sizeof tmp);

  msg->link_id = 0;
  if ((buf[0] == 0xFD) && (buf[2] & 0x1)) {
    msg->link_id = *p++;
    msg->timestamp = read_uint16(&p);
    msg->timestamp |= read_uint32(&p) << 16;
    msg->signature = read_uint16(&p);
    msg->signature |= read_uint32(&p) << 16;
  }

  return p - buf;
}

size_t python_array_test_message_seek(const uint8_t *buf, size_t size) {
  for (size_t r = 0; r < size; r++) {
    switch (buf[r]) {
    case 0xFD:
    case 0xFE:
      return r;
    }
  }
  return size;
}
