// Generated enums and structures for Mavlink dialect test #0 version 3
// Generated by gomavlink, DO NOT EDIT.
#include <stdarg.h>
#include <stdio.h>

#include "test.h"

static inline size_t psnprintf(char **pbuf, size_t *psize, const char *fmt,
                               ...) {
  va_list ap;
  va_start(ap, fmt);
  size_t s = vsnprintf(*pbuf, *psize, fmt, ap);
  if (s < *psize) {
    *pbuf += s;
    *psize -= s;
  } else {
    *psize = 0;
  }
  return s;
}

size_t test_message_snprintf(char *buf, size_t size,
                             const struct test_message *msg) {
  size_t r = 0;
  switch (msg->msg_id) {

  case TEST_MESSAGE_TEST_TYPES:

    r += psnprintf(&buf, &size, "TEST_TYPES<");

    r += psnprintf(&buf, &size, " u64:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s64:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " d:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " u64_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s64_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " d_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " u32:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s32:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " f:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " u32_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s32_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " f_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " u16:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s16:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " u16_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s16_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " c:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " u8:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s8:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " u8_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " s8_array:");
    // TODO values: handle strings, arrays and enums
    r += psnprintf(&buf, &size, " >");
    break;
  };

  return r;
}
