// Generated enums and structures for Mavlink dialect test #0 version 3
// Generated by gomavlink, DO NOT EDIT.

#include "test.h"

// Internal function used by both serialisation and deserialisation.
uint8_t test_crcextra(enum TEST_MESSAGE mid) {
  switch (mid) {
  case TEST_MESSAGE_TEST_TYPES:
    return 103;
  }
  return 0;
}
