// Code generated by "stringer -output strings.go -type=IcarousTrackBandTypes,IcarousFmsState"; DO NOT EDIT.

package icarous

import "strconv"

const _IcarousTrackBandTypes_name = "ICAROUS_TRACK_BAND_TYPE_NONEICAROUS_TRACK_BAND_TYPE_NEARICAROUS_TRACK_BAND_TYPE_RECOVERY"

var _IcarousTrackBandTypes_index = [...]uint8{0, 28, 56, 88}

func (i IcarousTrackBandTypes) String() string {
	if i >= IcarousTrackBandTypes(len(_IcarousTrackBandTypes_index)-1) {
		return "IcarousTrackBandTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IcarousTrackBandTypes_name[_IcarousTrackBandTypes_index[i]:_IcarousTrackBandTypes_index[i+1]]
}

const _IcarousFmsState_name = "ICAROUS_FMS_STATE_IDLEICAROUS_FMS_STATE_TAKEOFFICAROUS_FMS_STATE_CLIMBICAROUS_FMS_STATE_CRUISEICAROUS_FMS_STATE_APPROACHICAROUS_FMS_STATE_LAND"

var _IcarousFmsState_index = [...]uint8{0, 22, 47, 70, 94, 120, 142}

func (i IcarousFmsState) String() string {
	if i >= IcarousFmsState(len(_IcarousFmsState_index)-1) {
		return "IcarousFmsState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IcarousFmsState_name[_IcarousFmsState_index[i]:_IcarousFmsState_index[i+1]]
}
